### ISSUE TITLE
Can't currently build because of flate2

### ISSUE THREAD

**Issue by stevenroose** [rust-lang/cargo#10136]
### Problem

I have all the prerequisites mentioned in the Cargo contributing guilde: https://doc.crates.io/contrib/process/working-on-cargo.html#building-cargo

```
$ cargo build
   Compiling sized-chunks v0.6.5
   Compiling serde_json v1.0.39
   Compiling tempfile v3.2.0
   Compiling semver v1.0.4
   Compiling toml v0.5.8
   Compiling os_info v3.0.8
   Compiling serde_ignored v0.1.2
   Compiling cargo-platform v0.1.2 (/home/steven/code/rust/cargo/crates/cargo-platform)
   Compiling crypto-hash v0.3.3
   Compiling cargo v0.59.0 (/home/steven/code/rust/cargo)
   Compiling im-rc v15.0.0
   Compiling git2 v0.13.24
   Compiling cargo-util v0.1.1 (/home/steven/code/rust/cargo/crates/cargo-util)
error: failed to run custom build command for `cargo v0.59.0 (/home/steven/code/rust/cargo)`

Caused by:
  process didn't exit successfully: `/media/data/cargo-target/debug/build/cargo-c079119e759e589a/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'attempted to zero-initialize type `ffi::imp::z::z_stream`, which is invalid', /home/steven/.cargo/registry/src/github.com-1ecc6299db9ec823/flate2-1.0.6/src/ffi.rs:79:42
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:517:5
     1: core::panicking::panic_fmt
               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/panicking.rs:101:14
     2: core::panicking::panic
               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/panicking.rs:50:5
     3: core::mem::zeroed
               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/mem/mod.rs:629:9
     4: <flate2::ffi::imp::StreamWrapper as core::default::Default>::default
               at /home/steven/.cargo/registry/src/github.com-1ecc6299db9ec823/flate2-1.0.6/src/ffi.rs:79:42
     5: flate2::mem::Compress::new
               at /home/steven/.cargo/registry/src/github.com-1ecc6299db9ec823/flate2-1.0.6/src/mem.rs:202:29
     6: flate2::gz::write::gz_encoder
               at /home/steven/.cargo/registry/src/github.com-1ecc6299db9ec823/flate2-1.0.6/src/gz/write.rs:48:36
     7: flate2::gz::GzBuilder::write
               at /home/steven/.cargo/registry/src/github.com-1ecc6299db9ec823/flate2-1.0.6/src/gz/mod.rs:175:9
     8: build_script_build::compress_man
               at ./build.rs:17:19
     9: build_script_build::main
               at ./build.rs:7:5
    10: core::ops::function::FnOnce::call_once
               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/ops/function.rs:227:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by ehuss** [comment]
`flate2-1.0.6` looks quite old. Can you run `cargo update` and try again?

**Comment by stevenroose** [comment]
Oh, how come `Cargo.lock` is not checked in for cargo? Shouldn't it be checked in for binaries?

How else do we know what versions the release binaries are built with? And doesn't that make Cargo quite susceptible to regressions or malicious changes to any of its dependencies?

**Comment by stevenroose** [comment]
That worked.

**Comment by ehuss** [comment]
Cargo is built from the https://github.com/rust-lang/rust/ repository which has a `Cargo.lock` file that tracks cargo's dependencies.
