### ISSUE TITLE
Index out of bounds panic in `cargo doc --open` when building crate with no documentation

### ISSUE THREAD

**Issue by 5225225** [rust-lang/cargo#10194]
### Problem

`cargo doc --open` panics when ran in a crate without any crates with documentation.

```
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', src/tools/cargo/src/cargo/ops/cargo_doc.rs:23:21
stack backtrace:
   0: rust_begin_unwind
             at /rustc/928783de663bd855a96f14b2d38c1061603587c6/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/928783de663bd855a96f14b2d38c1061603587c6/library/core/src/panicking.rs:107:14
   2: core::panicking::panic_bounds_check
             at /rustc/928783de663bd855a96f14b2d38c1061603587c6/library/core/src/panicking.rs:75:5
   3: cargo::ops::cargo_doc::doc
   4: cargo::commands::doc::exec
   5: cargo::cli::execute_subcommand
   6: cargo::cli::main
   7: cargo::main
```

### Steps

1. Make a crate with `cargo init --lib`
2. Add the following to the Cargo.toml
```toml
[lib]
doc = false
```
3. Run `cargo doc --open`

### Possible Solution(s)

Cargo doc should print an error about not having any crates with documentation

### Notes

It also errors with a crate with a binary with no docs, but I assume fixing one will fix the other.

### Version

```text
cargo 1.58.0-nightly (40dc28175 2021-12-06)
release: 1.58.0
commit-hash: 40dc281755137ee804bc9b3b08e782773b726e44
commit-date: 2021-12-06
host: x86_64-unknown-linux-gnu
libgit2: 1.3.0 (sys:0.13.23 vendored)
libcurl: 7.80.0-DEV (sys:0.4.51+curl-7.80.0 vendored ssl:OpenSSL/1.1.1l)
os: Arch Linux Rolling Release [64-bit]
```

**Comment by Eh2406** [comment]
Indeed https://github.com/rust-lang/cargo/blob/master/src/cargo/ops/cargo_doc.rs#L23 should probably be a `get` that converts None to an error message.
