### ISSUE TITLE
`rustc` panic after running `cargo doc`, on on machine but not another

### ISSUE THREAD

**Issue by Ryan1729** [rust-lang/cargo#10233]
### Problem

When running `cargo doc`, even on a freshly created project I get a panic from `rustc`, and a `Unrecognized option: 'document-private-items'`. Note that this happens even if I do not explicitly add the `--document-private-items` flag.

The `rustc` error says: 
```
thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 0, error_len: Some(1) }', /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/compiler/rustc_serialize/src/opaque.rs:659:85
```

This happens on one Linux machine of mine, but if I try it on a different Linux machine, with the same version of cargo, the panic doesn't happen and the command executes successfully.
 
I don't know whether this is related, but one somewhat unusual UTF-8 related thing I was doing when I first noticed this issue was I was running cargo doc in a folder with a name containing the character `é`. (I had renamed the folder after creating the crate with a name with just a plain `e`)

### Steps

I am currently able to repeatedly reproduce this with the following steps on the affected machine:

```
cd /tmp
cargo new a
cd a
cargo doc
```

The output of the above but replacing `cargo doc` with `RUST_BACKTRACE=full cargo doc` follows:

```
 Documenting a v0.1.0 (/tmp/a)
thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 0, error_len: Some(1) }', /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/compiler/rustc_serialize/src/opaque.rs:659:85
stack backtrace:
   0:     0x7fc8701e4a9c - std::backtrace_rs::backtrace::libunwind::trace::hf6a6dfd7da937cb0
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x7fc8701e4a9c - std::backtrace_rs::backtrace::trace_unsynchronized::hc596a19e4891f7f3
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fc8701e4a9c - std::sys_common::backtrace::_print_fmt::hb16700db31584325
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7fc8701e4a9c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h231c4190cfa75162
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x7fc870241fdc - core::fmt::write::h2a1462b5f8eea807
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/fmt/mod.rs:1163:17
   5:     0x7fc8701d4c05 - std::io::Write::write_fmt::h71ddfebc68685972
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/io/mod.rs:1696:15
   6:     0x7fc8701e7f60 - std::sys_common::backtrace::_print::hcc197d4bebf2b369
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x7fc8701e7f60 - std::sys_common::backtrace::print::h335a66af06738c7c
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x7fc8701e7f60 - std::panicking::default_hook::{{closure}}::h6fac9ac9c8b79e52
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:210:50
   9:     0x7fc8701e7b15 - std::panicking::default_hook::h341c1030c6a1161b
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:227:9
  10:     0x7fc8709d42b1 - rustc_driver::DEFAULT_HOOK::{{closure}}::{{closure}}::h932547f60770f26a
  11:     0x7fc8701e8779 - std::panicking::rust_panic_with_hook::h50680ff4b44510c6
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:628:17
  12:     0x7fc8701e8230 - std::panicking::begin_panic_handler::{{closure}}::h9371c0fbb1e8465a
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:521:13
  13:     0x7fc8701e4f44 - std::sys_common::backtrace::__rust_end_short_backtrace::h9b3efa22a5768c0f
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:139:18
  14:     0x7fc8701e8199 - rust_begin_unwind
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
  15:     0x7fc8701ac441 - core::panicking::panic_fmt::h23b9203e89cc61cf
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
  16:     0x7fc8701ac533 - core::result::unwrap_failed::h32ef6b3156e8fc57
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/result.rs:1616:5
  17:     0x7fc872290117 - core::ops::function::FnOnce::call_once::h17b2f04c3ecefe60
  18:     0x7fc87228ef5d - rustc_span::hygiene::_DERIVE_rustc_serialize_Decodable_D_FOR_ExpnData::<impl rustc_serialize::serialize::Decodable<__D> for rustc_span::hygiene::ExpnData>::decode::hb40699411570388b
  19:     0x7fc872292e52 - rustc_metadata::rmeta::decoder::<impl rustc_serialize::serialize::Decodable<rustc_metadata::rmeta::decoder::DecodeContext> for rustc_span::hygiene::ExpnId>::decode::hb5be2d5420de38ee
  20:     0x7fc87228f905 - rustc_span::hygiene::_DERIVE_rustc_serialize_Decodable_D_FOR_SyntaxContextData::<impl rustc_serialize::serialize::Decodable<__D> for rustc_span::hygiene::SyntaxContextData>::decode::h27b23e5309d03030
  21:     0x7fc872292a4a - rustc_metadata::rmeta::decoder::<impl rustc_serialize::serialize::Decodable<rustc_metadata::rmeta::decoder::DecodeContext> for rustc_span::hygiene::SyntaxContext>::decode::h7ec1cf8eaae4e9d7
  22:     0x7fc87228b12f - rustc_metadata::rmeta::decoder::<impl rustc_serialize::serialize::Decodable<rustc_metadata::rmeta::decoder::DecodeContext> for rustc_span::span_encoding::Span>::decode::h82d6cb784ffe4969
  23:     0x7fc87224c8f7 - rustc_metadata::rmeta::decoder::<impl rustc_metadata::creader::CrateMetadataRef>::each_child_of_item::hf31798a84db343c8
  24:     0x7fc872d5a659 - rustc_metadata::rmeta::decoder::cstore_impl::provide_extern::associated_item_def_ids::hf20c6f46c15f1f46
  25:     0x7fc87212542c - rustc_query_system::query::plumbing::try_execute_query::h25a977204cd6e6b4
  26:     0x7fc8721bbaef - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::associated_item_def_ids::hc82ef87bc5be1387
  27:     0x7fc871e3c7e2 - rustc_ty_utils::ty::associated_items::hc203be4e65678c97
  28:     0x7fc87213a148 - rustc_query_system::query::plumbing::try_execute_query::h955f913eec29898d
  29:     0x7fc8721bbd86 - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::associated_items::hf71d96f5905ad2aa
  30:     0x55d487cb341c - rustdoc::clean::inline::build_impl::h9fffa0b1dc451d5e
  31:     0x55d487bef772 - rustdoc::passes::collect_trait_impls::collect_trait_impls::h6dc6a5694050575e
  32:     0x55d487cc07c8 - rustdoc::core::run_global_ctxt::h128b0174d8050763
  33:     0x55d487c75eea - rustc_interface::interface::create_compiler_and_run::hc072f2208fc21643
  34:     0x55d487b17ac1 - rustdoc::main_options::hfcbaaac935ed1410
  35:     0x55d487b26a4d - scoped_tls::ScopedKey<T>::set::hc630189ac37e10ce
  36:     0x55d487c7a349 - std::sys_common::backtrace::__rust_begin_short_backtrace::hdf9118cdbd94d4c4
  37:     0x55d487d42cc0 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h7507ab69c828f1bd
  38:     0x7fc8701f3933 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h7bd677a5dc988be6
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/alloc/src/boxed.rs:1691:9
  39:     0x7fc8701f3933 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h7b1c1ba11c4db785
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/alloc/src/boxed.rs:1691:9
  40:     0x7fc8701f3933 - std::sys::unix::thread::Thread::new::thread_start::h9c58c0d12d84e854
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys/unix/thread.rs:106:17
  41:     0x7fc870114609 - start_thread
                               at /build/glibc-YYA7BZ/glibc-2.31/nptl/pthread_create.c:477:8
  42:     0x7fc86febe103 - clone
  43:                0x0 - <unknown>

error: internal compiler error: unexpected panic

error: Unrecognized option: 'document-private-items'

error: could not document `a`

Caused by:
  process didn't exit successfully: `rustdoc --edition=2021 --crate-type bin --crate-name a src/main.rs -o /tmp/a/target/doc --error-format=json --json=diagnostic-rendered-ansi --document-private-items -L dependency=/tmp/a/target/debug/deps --crate-version 0.1.0` (exit status: 1)
```

### Possible Solution(s)

I'm just guessing, but since this only happens on on of my machines, maybe there's a system wide cache somewhere that has gotten messed up somehow? Is there a recommended way to clear any `cargo` caches?

### Notes

I'm not sure whether this is the same as https://github.com/rust-lang/cargo/issues/10225 or not. The output after the panic includes the following:
```
process didn't exit successfully: `rustdoc --edition=2021 --crate-type bin --crate-name a src/main.rs -o /tmp/a/target/doc --error-format=json --json=diagnostic-rendered-ansi --document-private-items -L dependency=/tmp/a/target/debug/deps --crate-version 0.1.0`
```
Which does include `--error-format=json` and `--document-private-items` which are similar to the set of flags that issue mentions.

### Version

```text
cargo 1.57.0 (b2e52d7ca 2021-10-21)
release: 1.57.0
commit-hash: b2e52d7cab0a286ee9fcc0c17510b1e72fcb53eb
commit-date: 2021-10-21
host: x86_64-unknown-linux-gnu
libgit2: 1.3.0 (sys:0.13.23 vendored)
libcurl: 7.79.1-DEV (sys:0.4.49+curl-7.79.1 vendored ssl:OpenSSL/1.1.1l)
os: Ubuntu 20.04 (focal) [64-bit]
```

**Comment by ehuss** [comment]
Hm, that's strange!   You can ignore the thing about `document-private-items`, that is just a bug in how a rustdoc ICE is reported.

Do you maybe have sccache or any other environment variables that may affect how cargo runs?  I'd check for any sort of wrappers or any cargo config files (on nightly you can run `cargo config get -Zunstable-options` to display all config files).  Does it also fail with the latest nightly?

**Comment by Ryan1729** [comment]
I have not installed `sccache`. after running `env` I don't see anything obviously Rust/Cargo related in my environment, besides `~/.cargo/bin`. being on my `PATH`.

After updating to the latest nightly, the following command, output pairs happen:

`cargo +nightly config get -Zunstable-options`:
```
# The following environment variables may affect the loaded values.
# CARGO_HOME=/home/ryan/.cargo
```

`RUST_BACKTRACE=full cargo +nightly doc`:
```
 Documenting a v0.1.0 (/tmp/a)
    Finished dev [unoptimized + debuginfo] target(s) in 1.45s
```

`cargo +nightly version --verbose`:
```
cargo 1.59.0-nightly (fcef61230 2021-12-17)
release: 1.59.0-nightly
commit-hash: fcef61230c3b6213b6b0d233a36ba4ebd1649ec3
commit-date: 2021-12-17
host: x86_64-unknown-linux-gnu
libgit2: 1.3.0 (sys:0.13.23 vendored)
libcurl: 7.80.0-DEV (sys:0.4.51+curl-7.80.0 vendored ssl:OpenSSL/1.1.1l)
os: Ubuntu 20.04 (focal) [64-bit]
```

Running just `cargo doc` on stable still panics the same way.

**Comment by ehuss** [comment]
My best guess is that maybe your stable toolchain got corrupted somehow?
Can you try reinstalling?  I think that would be `rustup toolchain uninstall stable` and then `rustup toolchain install stable`.

**Comment by Ryan1729** [comment]
I ran those commands, and now `cargo doc` works now, both in the blank test project, and in the project where I originally noticed the problem, so I guess that must have been it.

Thanks for your help!

**Comment by Ryan1729** [comment]
I ran those commands, and now `cargo doc` works now, both in the blank test project, and in the project where I originally noticed the problem, so I guess that must have been it.

Thanks for your help!

**Comment by Ryan1729** [comment]
I ran those commands, and now `cargo doc` works now, both in the blank test project, and in the project where I originally noticed the problem, so I guess that must have been it.

Thanks for your help!

**Comment by Ryan1729** [comment]
FWIW the SSD of the machine this issue happened on has now failed. So early corruption may have been the cause of this issue.
