### ISSUE TITLE
Cargo cann't be built in msys2.

### ISSUE THREAD

**Issue by o01eg** [rust-lang/cargo#1088]
Cargo cann't download snapshot in msys2 and fails to build:

```
$ make
/mingw64/bin/python src/etc/dl-snapshot.py x86_64-pc-windows-gnu
Traceback (most recent call last):
  File "src/etc/dl-snapshot.py", line 80, in <module>
    with urlopen(url) as in_file:
  File "src/etc/dl-snapshot.py", line 14, in <lambda>
    urlopen = lambda url: closing(urlopen2(url))
  File "E:/msys64/mingw64/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "E:/msys64/mingw64/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "E:/msys64/mingw64/lib/python2.7/urllib2.py", line 454, in _open
    'unknown_open', req)
  File "E:/msys64/mingw64/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "E:/msys64/mingw64/lib/python2.7/urllib2.py", line 1265, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib2.URLError: <urlopen error unknown url type: https>
Makefile:81: recipe for target 'target/snapshot/bin/cargo.exe' failed
make: *** [target/snapshot/bin/cargo.exe] Error 1
```

**Comment by gamma235** [comment]
I'm stuck with similar situation and am a newbie when it comes to command line scripts. I am using a mac with OSX. Below is the exact error I get  when I run `make`. What should I do to get this up and running?

    raceback (most recent call last):ot.py 
    File "src/etc/dl-snapshot.py", line 34, in <module>
    vendor = ts[1]
    IndexError: list index out of range
    make: *** [target/snapshot/bin/cargo] Error 1
