### ISSUE TITLE
thread 'main' panicked at 'not currently active!?', src/tools/cargo/src/cargo/core/resolver/mod.rs:832:36

### ISSUE THREAD

**Issue by dovahcrow** [rust-lang/cargo#11012]
### Problem

Tried to run cargo update with a large private project uses workspace and a bunch of crates.io patches. 

This is the full stacktrace:
```
thread 'main' panicked at 'not currently active!?', src/tools/cargo/src/cargo/core/resolver/mod.rs:832:36
stack backtrace:
   0:     0x5610dcd2b72d - std::backtrace_rs::backtrace::libunwind::trace::hb729d9642bb971eb
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x5610dcd2b72d - std::backtrace_rs::backtrace::trace_unsynchronized::h373bb774579df5c7
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5610dcd2b72d - std::sys_common::backtrace::_print_fmt::hfbd4e92d240c89bb
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x5610dcd2b72d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h8f618991fbf64972
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x5610dcd549ec - core::fmt::write::hc69b5b640d88cce8
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/fmt/mod.rs:1196:17
   5:     0x5610dcd23aa1 - std::io::Write::write_fmt::h3403cef06a24a303
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/io/mod.rs:1654:15
   6:     0x5610dcd2d745 - std::sys_common::backtrace::_print::h368f27cdedea0e52
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x5610dcd2d745 - std::sys_common::backtrace::print::ha105c9cf5a64cd17
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x5610dcd2d745 - std::panicking::default_hook::{{closure}}::h48ed2c3707d5e20e
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:295:22
   9:     0x5610dcd2d3b9 - std::panicking::default_hook::h8744fc5cea5e3110
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:314:9
  10:     0x5610dcd2dd18 - std::panicking::rust_panic_with_hook::hc82286af2030e925
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:698:17
  11:     0x5610dcd2dbc7 - std::panicking::begin_panic_handler::{{closure}}::h1c15057c2f09081f
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:588:13
  12:     0x5610dcd2bbe4 - std::sys_common::backtrace::__rust_end_short_backtrace::h65de906a5330f8da
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x5610dcd2d8f9 - rust_begin_unwind
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:584:5
  14:     0x5610dc2f6993 - core::panicking::panic_fmt::h741cfbfc95bc6112
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:142:14
  15:     0x5610dcd52791 - core::panicking::panic_display::h1094c8c253f473c8
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:72:5
  16:     0x5610dcd5273b - core::panicking::panic_str::hbdaf98ecbcb31da3
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:56:5
  17:     0x5610dc2f6806 - core::option::expect_failed::hf79a0c6dca04c0cf
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/option.rs:1854:5
  18:     0x5610dc43b971 - cargo[abdb6b117f51cade]::core::resolver::activate_deps_loop
  19:     0x5610dc4351f5 - cargo[abdb6b117f51cade]::core::resolver::resolve
  20:     0x5610dc807e54 - cargo[abdb6b117f51cade]::ops::resolve::resolve_with_previous
  21:     0x5610dc468c83 - cargo[abdb6b117f51cade]::ops::cargo_generate_lockfile::update_lockfile
  22:     0x5610dc34c4c5 - cargo[ff0cf4d108a6ca8]::commands::update::exec
  23:     0x5610dc33afaf - cargo[ff0cf4d108a6ca8]::cli::main
  24:     0x5610dc30016e - cargo[ff0cf4d108a6ca8]::main
  25:     0x5610dc3481d3 - std[62a6aef941a414a5]::sys_common::backtrace::__rust_begin_short_backtrace::<fn(), ()>
  26:     0x5610dc36e059 - std[62a6aef941a414a5]::rt::lang_start::<()>::{closure#0}
  27:     0x5610dcd1c15e - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hf833e7144973d4be
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/ops/function.rs:280:13
  28:     0x5610dcd1c15e - std::panicking::try::do_call::h79761d203bfb6b46
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:492:40
  29:     0x5610dcd1c15e - std::panicking::try::h0561cbbe1722251d
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:456:19
  30:     0x5610dcd1c15e - std::panic::catch_unwind::hbca347ddd031b141
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panic.rs:137:14
  31:     0x5610dcd1c15e - std::rt::lang_start_internal::{{closure}}::h0492050ad281ec32
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/rt.rs:128:48
  32:     0x5610dcd1c15e - std::panicking::try::do_call::h3ebce69871996bb3
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:492:40
  33:     0x5610dcd1c15e - std::panicking::try::hbed537d20e728475
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:456:19
  34:     0x5610dcd1c15e - std::panic::catch_unwind::h4185e2024c6a5d05
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panic.rs:137:14
  35:     0x5610dcd1c15e - std::rt::lang_start_internal::h1899cfd715ca6829
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/rt.rs:128:20
  36:     0x5610dc302032 - main
  37:     0x7fcd534fe0b3 - __libc_start_main
  38:     0x5610dc2f6cd9 - <unknown>
```

### Steps

Can't have a reproduce step for now since it is a large private repo. 

### Version

```text
cargo 1.62.0 (a748cf5a3 2022-06-08)
release: 1.62.0
commit-hash: a748cf5a3e666bc2dcdf54f37adef8ef22196452
commit-date: 2022-06-08
host: x86_64-unknown-linux-gnu
libgit2: 1.4.2 (sys:0.14.2 vendored)
libcurl: 7.80.0-DEV (sys:0.4.51+curl-7.80.0 vendored ssl:OpenSSL/1.1.1n)
os: Ubuntu 20.04 (focal) [64-bit]
```

**Comment by weihanglo** [comment]
Really sorry you bumped into this. However, without any additional info it's hard to move forward. Do you think is it possible to reduce to a minimal reproducible example? Could you describe how complex you did patches? What was changed between the last successful build and this panicking? Thank you.

**Comment by dovahcrow** [comment]
@weihanglo sure I'll try to reduce it down.

**Comment by Eh2406** [comment]
This is very exciting! The terrible error messages is because I could not imagine how the code could end up in such a mess. Somehow you hit https://github.com/rust-lang/cargo/blob/a77ed9ba87bfeaf3c2758a5b291876c65f734c39/src/cargo/core/resolver/mod.rs#L832 if we can get a way for me to reproduce, I am very much looking forward to debugging this.

You may want to backup a copy of the index in cargo_home and the patches, as they are also inputs to resolution that may affects repoducabilaty. That being said the actual contents of your project should not affect this error, if you copy your cargo.toml and cargo.lock into a `cargo new` project you should have the same problem.

**Comment by dovahcrow** [comment]
Sadly yesterday, I refactored some of the dependencies; I forgot which special combination of the packages could cause the issue. I'll close this for now and open the issue once I encounter the problem again.

**Comment by hw0lff** [comment]
I just encountered this error too. I have created a [minimal reproducible example](https://gitlab.com/w0lff/cargo-issue-11012) @Eh2406
