### ISSUE TITLE
panic when attempting to `cargo doc -p` a dev-dependency

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/cargo#11105]
### Problem

Panic occurs when attempting to build the docs of a crate added as a dev-dependency.

### Steps

```console
> cargo new cargo-11105 && cd cargo-11105 && cargo add --dev serde && RUST_BACKTRACE=1 cargo doc -p serde
     Created binary (application) `foo` package
    Updating crates.io index
      Adding serde v1.0.144 to dev-dependencies.
             Features:
             + std
             - alloc
             - derive
             - rc
             - serde_derive
             - unstable
thread 'main' panicked at 'activated_features for invalid package: features did not find PackageId { name: "serde", version: "1.0.144", source: "registry `crates-io`" } NormalOrDevOrArtifactTarget(None)', src/tools/cargo/src/cargo/core/resolver/features.rs:318:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c07a8b4e09f356c7468b69c50cac7fc5b5000b8a/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/c07a8b4e09f356c7468b69c50cac7fc5b5000b8a/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/c07a8b4e09f356c7468b69c50cac7fc5b5000b8a/library/core/src/result.rs:1785:5
   3: cargo::ops::cargo_compile::generate_targets
   4: cargo::ops::cargo_compile::create_bcx
   5: cargo::ops::cargo_compile::compile_ws
   6: cargo::ops::cargo_compile::compile
   7: cargo::ops::cargo_doc::doc
   8: cargo::commands::doc::exec
   9: cargo::cli::main
  10: cargo::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Version

```text
cargo 1.65.0-nightly (6da726708 2022-08-23)
release: 1.65.0-nightly
commit-hash: 6da726708a4406f31f996d813790818dce837161
commit-date: 2022-08-23
host: x86_64-unknown-linux-gnu
libgit2: 1.4.2 (sys:0.14.2 vendored)
libcurl: 7.83.1-DEV (sys:0.4.55+curl-7.83.1 vendored ssl:OpenSSL/1.1.1q)
os: Arch Linux [64-bit]
```

**Comment by hi-rustin** [comment]
@rustbot claim
I can reproduce it. I will take a look and try to fix it.

**Comment by hi-rustin** [comment]
I debugged it. I found the cause of the panic is we do not contain the package information in https://github.com/rust-lang/cargo/blob/13ae438cf079da58272edc71f4d4968043dbd27b/src/cargo/core/resolver/features.rs#L55

**Comment by hi-rustin** [comment]
Do we really support this feature?
Because I found the reason for [this information missing](https://github.com/rust-lang/cargo/issues/11105#issuecomment-1257402437) is we set `opts.decouple_dev_deps` to true. 

If we set the `opts.decouple_dev_deps` to false, it works well.

Also, if you have the same dep in both dep and dev-dep. It also works.
```toml
[package]
name = "foo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.145"

[dev-dependencies]
serde = "1.0.145"
```

```log
➜  foo git:(master) ✗ RUST_BACKTRACE=1 cargo doc -p serde
 Documenting serde v1.0.145
    Finished dev [unoptimized + debuginfo] target(s) in 3.08s
```

**Comment by Nemo157** [comment]
Ah, that reminds me of something I should have checked. This only panics on `edition = "2021"`. Also `cargo +1.51 doc -p serde` doesn't seem to have Edition 2021 gated and successfully creates the docs 🤔. Every version after that which supports Edition 2021 panics.

**Comment by weihanglo** [comment]
You're right. That's the reason this issue is labelled as <https://github.com/rust-lang/cargo/labels/A-features2>. My impression is that the new feature resolver only enables features for dev-dependencies if they are actually needed to build tests/benches/examples.

I guess `cargo doc -p <build-denpendency>` also panics with the same reason.

**Comment by hi-rustin** [comment]
> My impression is that the new feature resolver only enables features for dev-dependencies if they are actually needed to build tests/benches/examples.

Yes.  That's why I asked if we support this feature in feature2. For now, it looks like we do not want to enable dev-dep by design.

**Comment by Nemo157** [comment]
IMO it's an important usecase, when you are developing offline and need to check the API documentation of your `dev-dependencies`. There are workarounds like temporarily adding them to your `dependencies`, or adding an example and using `cargo doc --examples` (though this builds docs for all dev-dependencies, not just whichever one you are interested in), but it seems like it should just work.

**Comment by hi-rustin** [comment]
@weihanglo How about when we find out that this package is a development dep package and we set it to yes?
https://github.com/rust-lang/cargo/blob/b2ee005824eff89f1c99a3cecf91e1fd552d1979/src/cargo/ops/cargo_compile.rs#L383

But I don't know how to determine if this pkg is a dev-dep in here.

**Comment by weihanglo** [comment]
@hi-rustin, I feel like it is a larger issue than we thought. 

As far as I know, with feature resolver v2, Cargo runs the feature resolution in two passes:

* The first pass activates features without decoupling `dev-dependencies`, `build-dependencies`, and targets specified dependencies. This happens during the dependency resolution.
* The second pass narrows down the activated features set. This happens after the dependency resolution. This happens when explicitly enabling “resolver = 2" or in Edition 2021.

As a result, the [issue you found] starts happening after the second pass strips down “unnecessary” features. Currently, Cargo determines whether to unify feature based on the followings:

* For dev deps, [`CompileFilter::need_dev_deps`] does the job. However it only takes `CompileMode` into account.
* For target specified deps, you cannot activate their features unless you're building for those targets. Almost all code path set [`force_all_targets`] to `ForceAllTargets::No`, except `cargo metadata` and `cargo tree`.
* For build deps (host deps), they are always [decoupled from normal deps], unless [they are proc macros].

The problem is not only `cargo doc` but all cargo commands related to feature resolution. At least all [build commands] would panic by doing so. When a user specifies a package with `-p|--package`, it brings some design questions, such like:

* Do we expect `cargo build -p <dev-dep|build-dep>` to work?
* Do we expect `cargo doc -p <dev-dep|build-dep>` to work?
* Do we expect `cargo test -p <dev-dep|build-dep>` to work?
  (Except they also requires dev-deps, which [is already handled here])
* What does it mean to `cargo fix -p <dev-dep|build-dep>` if they are non-local deps?
* Cargo might tell user to pass `--target` when executing `cargo test -p <target-specified-dep>`.
* `cargo doc -p <target-specified-dep>` might also want to suggest `--target` if possible.
* Should we treat a certain command special in terms of feature unification?
  (I don't think so as it might break something but <https://github.com/rust-lang/cargo/labels/Z-scrape-examples> already diverged AFAIK)

[issue you found]: https://github.com/rust-lang/cargo/issues/11105#issuecomment-1257402437
[`CompileFilter::need_dev_deps`]: https://github.com/rust-lang/cargo/blob/b2ee005824eff89f1c99a3cecf91e1fd552d1979/src/cargo/ops/cargo_compile.rs#L870-L888
[`force_all_targets`]: https://github.com/rust-lang/cargo/blob/b2ee005824eff89f1c99a3cecf91e1fd552d1979/src/cargo/ops/resolve.rs#L160
[decoupled from normal deps]: https://github.com/rust-lang/cargo/blob/b2ee005824eff89f1c99a3cecf91e1fd552d1979/src/cargo/core/resolver/features.rs#L210
[they are proc macros]: https://github.com/rust-lang/cargo/blob/b2ee005824eff89f1c99a3cecf91e1fd552d1979/src/cargo/core/resolver/features.rs#L480-L489
[build commands]: https://doc.rust-lang.org/nightly/cargo/commands/build-commands.html
[already there]: https://github.com/rust-lang/cargo/blob/b2ee005824eff89f1c99a3cecf91e1fd552d1979/src/cargo/ops/cargo_compile.rs#L439-L443
[is already handled here]: https://github.com/rust-lang/cargo/blob/b2ee005824eff89f1c99a3cecf91e1fd552d1979/src/cargo/ops/cargo_compile.rs#L439-L443

---

Here is a demo Cargo.toml that you can tweak `resolver` to see the difference between v1 and v2.

- 🤯 `cargo check -p cfg-if`
- 🤯 `cargo check -p autocfg`
- ✅ `cargo check -p serde_derive`
- 🤯 `cargo check -p empty-library`
- ✅ `cargo check -p empty-library --target <target>`


```toml
[package]
name = "issue11105"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dev-dependencies]
cfg-if = "1"

[build-dependencies]
autocfg = "1"
serde_derive = "1"

[target.a-valid-target-triple.dependencies]
empty-library = "1"
```

**Comment by hi-rustin** [comment]
Yes. I am also considering do we really need to support this. Also, can this behavior change be considered an incompatible change? Otherwise, I think we'd better be able to handle it, at least not panic.

**Comment by weihanglo** [comment]
I'll bring this to the next triage meeting if there is any available slot. 

@Nemo157, @hi-rustin or anyone, if you've got more thoughts on this, please let us me. Thank you!

**Comment by hi-rustin** [comment]
@weihanglo Any progress on this issue? Thank you!

**Comment by ColinFinck** [comment]
I also hit this problem in a slightly different context. Turns out, it affects any cargo command when using `-p` on a dev dependency (`cargo build`, `cargo clippy`, `cargo doc`, ...)

Minimum `Cargo.toml` to reproduce:

```
[package]
name = "cargo-panic"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
anyhow = "1"
```

Then try e.g. `cargo build -p anyhow`

No matter if you decide to support this or not, cargo shouldn't panic here.
I can also confirm that `edition = "2018"` works fine.

**Comment by jyn514** [comment]
I ran into this for a normal dependency as well, not a dev-dependency.

Reproduction steps:
```
; cargo  add async-trait@0.1.68
; cargo  build -p proc-macro2
thread 'main' panicked at 'activated_features for invalid package: features did not find PackageId { name: "proc-macro2", version: "1.0.56", source: "registry `crates-io`" } NormalOrDev', src/tools/cargo/src/cargo/core/resolver/features.rs:321:14
```

**Comment by weihanglo** [comment]
<https://github.com/rust-lang/cargo/issues/15756> shows an instance of this happening to `cargo rustdoc`.
