### ISSUE TITLE
-Zrustdoc-scrape-examples crash if a package contains proc-macro library and example crate

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/cargo#11496]
### Problem

https://github.com/rust-lang/docs.rs/pull/1954 enabled `-Zrustdoc-scrape-examples`, which caused docs of the `automod` crate to fail to build.

https://docs.rs/crate/automod/1.0.5/builds/703499

```console
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/tools/cargo/src/cargo/ops/cargo_compile/mod.rs:595:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Steps

```toml
# Cargo.toml

[package]
name = "repro"
version = "0.0.0"
edition = "2021"

[lib]
proc-macro = true
```

```rust
// src/lib.rs (empty)
```

```rust
// examples/ex.rs

fn main() {}
```

```console
$ cargo +nightly-2022-12-18 rustdoc -Zrustdoc-scrape-examples
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/tools/cargo/src/cargo/ops/cargo_compile/mod.rs:595:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

If the library crate is not a proc macro, **or** if there is no example crate included in the package, then it does not crash.

### Notes

FYI @willcrichton

### Version

```text
cargo 1.68.0-nightly (cc0a32087 2022-12-14)
release: 1.68.0-nightly
commit-hash: cc0a320879c17207bbfb96b5d778e28a2c62030d
commit-date: 2022-12-14
host: x86_64-unknown-linux-gnu
libgit2: 1.5.0 (sys:0.15.0 vendored)
libcurl: 7.86.0-DEV (sys:0.4.59+curl-7.86.0 vendored ssl:OpenSSL/1.1.1q)
os: Ubuntu 22.04 (jammy) [64-bit]
```

**Comment by willcrichton** [comment]
Thanks for the report @dtolnay I will investigate this today. Your minimal example did not reproduce the issue on my machine, but I cloning the `automod` repo and running did.
