### ISSUE TITLE
`cargo chef cook` panics.  failed to download `cfg-if v1.0.0`.

### ISSUE THREAD

**Issue by srasku** [rust-lang/cargo#11595]
### Problem

I am using the following `Dockerfile` to test `cargo chef`.  In the long run I want to use it to cache Docker layers so that crates don't have to be downloaded every time I do a `docker build`.
```
FROM rust:1

RUN cargo install cargo-chef --locked

RUN cargo init --name bugreport
RUN cargo add byteorder
RUN cargo add rand
RUN cargo add get_if_addrs

RUN cargo chef prepare --recipe-path recipe.json
ENV RUST_BACTRACE=1
RUN cargo chef cook --recipe-path recipe.json
```

I get the following result.
```
$ DOCKER_BUILDKIT=0 docker build -t cargo-chef/bugreport .
Sending build context to Docker daemon  14.85kB
Step 1/9 : FROM rust:1
 ---> 5e0d0367026b
Step 2/9 : RUN cargo install cargo-chef --locked
 ---> Using cache
 ---> d2724f8cc24a
Step 3/9 : RUN cargo init --name bugreport
 ---> Using cache
 ---> 9ab4ad993c84
Step 4/9 : RUN cargo add byteorder
 ---> Using cache
 ---> be29bf13c189
Step 5/9 : RUN cargo add rand
 ---> Using cache
 ---> 1a01dfe59bd7
Step 6/9 : RUN cargo add get_if_addrs
 ---> Using cache
 ---> 2a3b579ad167
Step 7/9 : RUN cargo chef prepare --recipe-path recipe.json
 ---> Using cache
 ---> 5930f257c123
Step 8/9 : ENV RUST_BACTRACE=1
 ---> Running in d1d298a71c7c
Removing intermediate container d1d298a71c7c
 ---> 4c31683a91ba
Step 9/9 : RUN cargo chef cook --recipe-path recipe.json
 ---> Running in f0af46c26106
 Downloading crates ...
error: failed to download `cfg-if v1.0.0`

Caused by:
  unable to get packages from source

Caused by:
  failed to find cfg-if v1.0.0 in path source
note: this is an unexpected cargo internal error
note: we would appreciate a bug report: https://github.com/rust-lang/cargo/issues/
note: cargo 1.66.0 (d65d197ad 2022-11-15)
thread 'main' panicked at 'Exited with status code: 101', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/cargo-chef-0.1.51/src/recipe.rs:176:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
The command '/bin/sh -c cargo chef cook --recipe-path recipe.json' returned a non-zero code: 101
```

### Steps

1. `DOCKER_BUILDKIT=0 docker build -t cargo-chef/bugreport .`

### Version

```text
cargo 1.66.0 (d65d197ad 2022-11-15)
release: 1.66.0
commit-hash: d65d197ad5c6c09234369f219f943e291d4f04b9
commit-date: 2022-11-15
host: x86_64-unknown-linux-gnu
libgit2: 1.5.0 (sys:0.15.0 vendored)
libcurl: 7.83.1-DEV (sys:0.4.55+curl-7.83.1 vendored ssl:OpenSSL/1.1.1q)
os: Linux [64-bit]
```

**Comment by srasku** [comment]
Fixed the spelling of `RUST_BACKTRACE`:
```
Step 9/9 : RUN cargo chef cook --recipe-path recipe.json
 ---> Running in 47bfeb4ddf50
 Downloading crates ...
error: failed to download `cfg-if v1.0.0`

Caused by:
  unable to get packages from source

Caused by:
  failed to find cfg-if v1.0.0 in path source
note: this is an unexpected cargo internal error
note: we would appreciate a bug report: https://github.com/rust-lang/cargo/issues/
note: cargo 1.66.0 (d65d197ad 2022-11-15)
thread 'main' panicked at 'Exited with status code: 101', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/cargo-chef-0.1.51/src/recipe.rs:176:27
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at ./rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:65:14
   2: chef::recipe::Recipe::cook
   3: cargo_chef::_main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by epage** [comment]
`cargo chef` is creating a package and then calling into `cargo` to build it.

Could you narrow down the reproduction steps to just `cargo`, possibly by looking at the code generated by `cargo chef`?

**Comment by srasku** [comment]
@epage Where can I find the code generated by `cargo chef`?  I have to get it out of the container since the problem doesn't occur on the host.

**Comment by epage** [comment]
I do not know, I am unfamiliar with this cargo plugin.

**Comment by epage** [comment]
The panic is in `cook`
```
   2: chef::recipe::Recipe::cook
   3: cargo_chef::_main
```

[`cook`](https://github.com/LukeMathWalker/cargo-chef/blob/main/src/recipe.rs#L51) calls `build_dependencies` which calls into `cargo` which is where I'm assuming the error is coming from.

What it is building is generated by [`build_minimal_project`](https://github.com/LukeMathWalker/cargo-chef/blob/main/src/skeleton/mod.rs#L67)

**Comment by weihanglo** [comment]
There are some assumptions Cargo makes upon the current workding directory. Sorry for not being able to recall the exact one causing this issue 😞. 

The best practice I can provide is always creating a new level of directory as your `WORKDIR`. It should fix the problem. Also recommend following [the example code from README](https://github.com/LukeMathWalker/cargo-chef/blob/5c9f11578a2e0783cce27666737d50f84510b8b5/README.md?plain=1#L94-L114) of `cargo-chef`. It does some sane setup like multi-stage build.

```patch
  FROM rust:1

+ WORKDIR app

  RUN cargo install cargo-chef --locked

  RUN cargo init --name bugreport
  RUN cargo add byteorder
  RUN cargo add rand
  RUN cargo add get_if_addrs

  RUN cargo chef prepare --recipe-path recipe.json
  ENV RUST_BACTRACE=1
  RUN cargo chef cook --recipe-path recipe.json
```

**Comment by weihanglo** [comment]
Going to close this, as the workaround https://github.com/rust-lang/cargo/issues/11595#issuecomment-1398254631 should be sufficient to fix it. If that is a mistake, let us know and we'll consider reopening.
