### ISSUE TITLE
Error: failed to run custom build command for `libc v0.2.139`, but the problem seems deeper

### ISSUE THREAD

**Issue by pinghajen** [rust-lang/cargo#11591]
### Problem

I've been going through [the Rust Book](https://doc.rust-lang.org/stable/book/). I did `cargo new learning` to create the new project. `cargo build` worked and I was able to execute the default "Hello, world!" program no problem, but when I did `cargo run` I get this error:

       Compiling learning v0.1.0 (/home/.../rust/learning)
        Finished dev [unoptimized + debuginfo] target(s) in 0.63s
         Running `target/debug/learning`
    error: could not execute process `target/debug/learning` (never executed)
    
    Caused by:
      Invalid argument (os error 22)

Which was weird and I couldn't really find a solution to online. So, I decided to just execute the executables manually while I'm still going through the book.

I get to the [guessing game](https://doc.rust-lang.org/stable/book/ch02-00-guessing-game-tutorial.html) chapter. I can get it to accept my input and output it. But as soon as I add 

    [dependencies]
    rand = "0.8.5"

to my Cargo.toml and try `cargo build` I get this error:

       Compiling libc v0.2.139
       Compiling cfg-if v1.0.0
       Compiling ppv-lite86 v0.2.17
    error: failed to run custom build command for `libc v0.2.139`
    
    Caused by:
      could not execute process >`/home/.../rust/guessing_game/target/debug/build/libc-cef4b0a34c67eecd/build-script-build` (never executed)
    
    Caused by:
      Invalid argument (os error 22)

Even after a `cargo clean`

Eventually I get someone to help me. He eventually suggests to run `RUST_BACKTRACE=1 ./target/debug/build/libc->cef4b0a34c67eecd/build-script-build` which produced this:

    /build-script-build
    cargo:rerun-if-changed=build.rs
    thread 'main' panicked at 'Failed to get rustc version', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.139/build.rs:125:17
    stack backtrace:
       0: std::panicking::begin_panic
                 at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:607:12
       1: build_script_build::rustc_minor_nightly
                 at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.139/build.rs:125:17
       2: build_script_build::main
                 at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.139/build.rs:9:41
       3: core::ops::function::FnOnce::call_once
                 at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/ops/function.rs:251:5
    >note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

At this point he suggests I check my path:

    /home/user/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

And if I run rustc it does a help output and seems to be in my path. The guy who was helping my suggested to reinstall my distro because a few months previous I broke libc and he thought that might fix it. All of this is was reproduced on my new distro after I installed the software I use and updated it.

Looking online finds people with similar errors but it seems for different libraries that they just need to apt install.

Cargo.toml

    [package]
    name = "guessing_game"
    version = "0.1.0"
    edition = "2021"
    
    # See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
    
    [dependencies]
    rand = "0.8.5"

### Steps

I have no idea, I installed with rustup and it just didn't work out of the box

### Version

```text
cargo 1.66.1 (ad779e08b 2023-01-10)
release: 1.66.1
commit-hash: ad779e08be893e57a9e17a810223a3e966f8c0d8
commit-date: 2023-01-10
host: x86_64-unknown-linux-gnu
libgit2: 1.5.0 (sys:0.16.0 vendored)
libcurl: 7.83.1-DEV (sys:0.4.55+curl-7.83.1 vendored ssl:OpenSSL/1.1.1q)
os: Ubuntu 22.10 (kinetic) [64-bit]
```

**Comment by weihanglo** [comment]
I feel sorry for this bad issue. https://github.com/rust-lang/cargo/issues/11367 and https://github.com/rust-lang/cargo/issues/11512 are probably related, yet we don't have such bandwidth or domain expert to debug that at this moment 😞.

**Comment by pinghajen** [comment]
Some more information. @weihanglo linked 2 issues, both of which mention a samba share. This is in a network folder on a Windows host. I went to a copy it with

    cp -R guessing_game/ ~

and got:

    cp: cannot open 'guessing_game/target/debug/build/libc-cef4b0a34c67eecd/build_script_build-cef4b0a34c67eecd' for reading: Invalid argument

After doing a 

    cargo clean

the cp command worked as expected.

When on my local machine cargo just works as intended. The problem definitely appears to be network folders.

My `/etc/fstab` entry for this mount

    //IP/FOLDER /home/USER/FOLDER cifs auto,users,rw,credentials=/home/USER/.smbcredentials,iocharset=utf8,uid=1000,gid=1000,_netdev,exec,mfsymlinks 0 0

I also wonder if `mfsymlinks` is the culprit? I need it because the drive is in a Windows box or because it's formatted NTFS (I don't exactly remember the reason for mfsymlinks, just remember it does symlinks on Windows partitions).

**Comment by HerrWeber** [comment]
[https://github.com/rust-lang/cargo/issues/11512#issuecomment-1561976704](https://github.com/rust-lang/cargo/issues/11512#issuecomment-1561976704)
I left a comment with some info I think its related in the previous link. it might be related to file privileges.
