### ISSUE TITLE
More helpful error message when a stray `Cargo.toml` is present

### ISSUE THREAD

**Issue by kpreid** [rust-lang/cargo#13904]
### Problem

Newcomers to Cargo occasionally end up with a `Cargo.toml` file that is irrelevant to the project they're trying to run. (It is often in their home directory; perhaps they ran `cargo init` not understanding what it does, but that's speculation.) When this happens, they get an error message that doesn't really explain what is going on. An example from today:

```
$ cargo run
error: failed to parse manifest at '/home/user/Cargo.toml'

Caused by:
  this virtual manifest specifies a 'dependencies' section, which is not allowed
```

New users don't know what a “virtual manifest” is, and are dealing with too many new concepts already to notice that `/home/user/Cargo.toml` isn't their project directory, nor do they know that it doesn't make sense to have one there.

### Proposed Solution

Two parts:

1. When Cargo produces an error, the error is related to an invalid workspace manifest, and the purported workspace manifest path was found in a parent directory (rather than being the direct output of the [`locate-project` algorithm](https://doc.rust-lang.org/cargo/commands/cargo-locate-project.html)), produce a message which prints the paths of *both* manifests rather than only the workspace manifest, with some explanation that these are two different manifests and how each relates to the situation.

2. If the purported workspace manifest is at least two levels up from the project manifest, or is located in the user's home directory, produce an additional help message which speculates that the workspace manifest may be extraneous and should then be either deleted or relocated to avoid nesting unrelated projects.

### Notes

@rustbot label +A-diagnostics +A-workspaces +E-easy

**Comment by epage** [comment]
I just tried to reproduce this and didn't get any errors.  Could you provide more concrete reproduction steps and use cases that lead to these mistaken workspace manifests so we can better consider how the user gets into these situations so we understand what errors to look at and how to improve them?

**Comment by kpreid** [comment]
I can't provide concrete steps for the original example, because the user that had that problem didn't tell us how they got there. In general, issues of this type come from users that _don't_ remember what they did, or don't have enough model of Cargo to say what the relevant things they did are. But here is an example sequence of steps which will produce a (different) broken configuration:

```sh
$ cargo init
    Creating binary (application) package
note: see more `Cargo.toml` keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
$ rm -r src/ # we decided we didn't want this but didn't notice the other file
$ cargo new foo
    Creating binary (application) `foo` package
      Adding `foo` as member of workspace at `/<...>/project-structure-test`
warning: compiling this new package may not work due to invalid workspace configuration

failed to parse manifest at `/<...>/project-structure-test/Cargo.toml`

Caused by:
  no targets specified in the manifest
  either src/lib.rs, src/main.rs, a [lib] section, or [[bin]] section must be present
note: see more `Cargo.toml` keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
$ # IDK what that warning means so I will ignore it
$ cd foo
$ cargo check
error: failed to parse manifest at `/<...>/project-structure-test/Cargo.toml`

Caused by:
  no targets specified in the manifest
  either src/lib.rs, src/main.rs, a [lib] section, or [[bin]] section must be present
```

To be clear, this _is_ an unreasonable sequence of things to do all at once. Imagine, in between the parts, a lot of poking around with file managers and/or editors, trying different `cargo` commands, and possibly even moving files to different directories (“oh, I don't want my source code _here_…”). New users *don't know what matters* and I'm proposing that, for manifest errors involving supposed workspace manifests, Cargo can do a better job of mentioning what things *do* matter.

**Comment by epage** [comment]
So what you are wanting to see is something like
```diff
$ cargo check
-error: failed to parse manifest at `/<...>/project-structure-test/Cargo.toml`
+error: Could not parse workspace for ...
+
+Caused by:
+    failed to parse manifest at `/<...>/project-structure-test/Cargo.toml`

Caused by:
  no targets specified in the manifest
  either src/lib.rs, src/main.rs, a [lib] section, or [[bin]] section must be present
```

**Comment by epage** [comment]
Experimented with this a bit and not thrilled with the results
```
failures:

---- workspaces::error_if_parent_cargo_toml_is_invalid stdout ----
running `/home/epage/src/personal/cargo/target/debug/cargo check`
thread 'workspaces::error_if_parent_cargo_toml_is_invalid' panicked at tests/testsuite/workspaces.rs:1420:10:

test failed running `/home/epage/src/personal/cargo/target/debug/cargo check`
error: stderr did not match:
1   1     error: expected `.`, `=`
2   2      --> ../Cargo.toml:1:9
3   3       |
4   4     1 | Totally not a TOML file
5   5       |         ^
6   6       |
    7    +error: could not parse workspace for /home/epage/src/personal/cargo/target/tmp/cit/t35/foo/bar/Cargo.toml


other output:


note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- workspaces::new_warning_with_corrupt_ws stdout ----
running `/home/epage/src/personal/cargo/target/debug/cargo new bar`
thread 'workspaces::new_warning_with_corrupt_ws' panicked at tests/testsuite/workspaces.rs:1147:10:

test failed running `/home/epage/src/personal/cargo/target/debug/cargo new bar`
error: stderr did not match:
1   1         Creating binary (application) `bar` package
2   2     error: expected `.`, `=`
3   3      --> Cargo.toml:1:5
4   4       |
5   5     1 | asdf
6   6       |     ^
7   7       |
8   8     warning: compiling this new package may not work due to invalid workspace configuration
9   9
    10   +could not parse workspace for /home/epage/src/personal/cargo/target/tmp/cit/t58/foo/bar/Cargo.toml
10  11    note: see more `Cargo.toml` keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
```

Part of the problem is that annotate-snippets reporting is handled very differently than other errors and its less ideal in this situation.  We are also wanting to move as many errors to annotate-snippets as possible.

**Comment by kpreid** [comment]
> So what you are wanting to see is …

More like this:

> error: failed to parse manifest at `/<...>/project-structure-test/Cargo.toml`
>
> help: the current directory, `/<...>/project-structure-test/foo/`, contains a `Cargo.toml` manifest file, but is considered a workspace member due to the presence of a manifest file in the parent directory, but that file is currently not a valid workspace manifest. If `foo` is not intended to be part of a larger project, then move `foo/` out of `project-structure-test/` or remove the `Cargo.toml` file from `project-structure-test/`.

**Comment by epage** [comment]
Whichever way, that runs into the same problems.  More even since we can't add `help:` to regular errors, only annotate-snippet errors.  We sometimes emulate it but the result isn't the best.

btw that `help:` is too long that it would just lose people.

**Comment by onkoe** [comment]
I'd enjoy something simple, like: 

```
error: Failed to parse a package description in this workspace's Cargo.toml file.

Caused by:
	the surrounding workspace doesn't match its Cargo.toml file. 
``` 

That moves away from the "workspace manifest" terminology while remaining helpful for more-experienced users. 

If there is a way to add a `help` section, and we can tell if there's some issue with the package location, I'd like to see something similar to this: 

```
help: Try checking the placement of your Cargo.toml file and its packages. 
```

Also, if you do wish to continue using the manifest terminology, linking to the glossary may be neccessary: https://doc.rust-lang.org/cargo/appendix/glossary.html#manifest

In any case, if you have any advice for my input, please let me know! I'm looking to contribute more to Cargo and Rust in general. 😄

**Comment by dylanopen** [comment]
I stumbled across this thread trying to fix the same problem but for a different reason. For some reason, I'd accidentally deleted a character of the 'package' TOML header so it read 'packag'.

All fixed now, but I wanted to know why Cargo just blindly accepted `[packag]` as a heading instead of throwing an error / warning about an unrecognised keyword.

Furthermore, why does Cargo just assume it's a virtual workspace just because the `[package]` header is missing? Any answers are appreciated :)

``` toml
[packag]
name = "li"
version = "0.0.2"
edition = "2021"

[dependencies]
bevy = { version = "0.14.0", features = ["dynamic_linking"] }
serde = "1.0.204"

...

opt-level = 3
```

**Comment by epage** [comment]
> I wanted to know why Cargo just blindly accepted [packag] as a heading instead of throwing an error / warning about an unrecognised keyword.

Instead of erroring on unused keys, Cargo warns.  This is helpful when we are adding new functionality to `Cargo.toml` that doesn't otherwise require an MSRV bump, like adding `[lints]`.

> Furthermore, why does Cargo just assume it's a virtual workspace just because the [package] header is missing? 

A package must have at least
- `[package]` (or `[project]`)
- `[workspace]`

I can see improving the error if neither is present, rather than falling through to assuming its a virtual workspace.

**Comment by dylanopen** [comment]
@epage Thanks for the info!

**Comment by onkoe** [comment]
After taking a look into fixing this, it appears that the way Cargo stores data during manifest parsing isn't... optimal. 

There are a TON of free functions that take in data. That data could easily be held by some struct instead. Also, it's relatively difficult to tell which functions clone the data passed in, which can obfuscate what's going on when optimizing parsing.

Beyond that, a refactor would allow for better error messages - we could have multiple types which are constructed only when we've hit a certain step during data collection, allowing for fleshed-out errors with stronger diagnostics.

I've been playing with this kind of design in my spare time, including with my most recent crate. It's nice to keep things clean and have easy access to errors. For Cargo, it would seriously clean up `resolve_toml` and many of its friends to work on an `UnfinishedManifest` instead of countless passed references.

Has anyone spoken about similar changes in the past? If so, how did things go? 

Cleaning things up would help enable future improvements in this space. :)

**Comment by epage** [comment]
@onkoe this might be a case where people have different priorities wrt "clean code".

I just recently did massive refactors to all of that code to make it what it currently is.  That doesn't mean its ideal but I'm not sold on the areas you are talking about
- I prefer more precise information on what a function needs than providing a "god type"
- free functions make it clearer what state they mutate (and you don't have to worry about what type to associate them with)

> obfuscate what's going on when optimizing parsing.

If you are optimizing `clone`s, then you are likely trying to optimize the wrong thing.

> Beyond that, a refactor would allow for better error messages - we could have multiple types which are constructed only when we've hit a certain step during data collection, allowing for fleshed-out errors with stronger diagnostics.

I don't see how the changes you mentioned would help with error reporting.

**Comment by onkoe** [comment]
Thank you for the swift reply! I saw the refactor when skimming the commits - it already did a lot to aid accessibility. However, I see some additional changes that could help avoid large function calls.

A very basic idea of the transitions would be something like: (TOML) -> `UncheckedManifest` -> `Manifest`, where `UncheckedManifest` has methods to create the necessary fields on `Manifest`. It would contain lots of the existing free functions as methods, allowing for patterns like: `let dependencies = unchecked.resolve_dependencies()?;`.

## State Transitions

There are some issues with doing a one-to-one mapping of the free functions, though, as some rely on being called in certain contexts, after you parse things you'd put in its parameters. In that case, you can either continue with that pattern, or make additional states to represent their requirements. 

The latter of these options is helpful when adding new features (or errors), as you'd need to add another state transition to put in an additional level of parsing.

For errors in particular, this prevents unrelated ones (like "this virtual manifest specifies a 'dependencies' section") from being created outside their types. It would make something like checking if we're at a weird location more obvious:

```rust
// this is what we'll have by the end. all of its 
enum FinishedManifest {
    VirtualWorkspace(VirtualWorkspaceManifest),
    Workspace(WorkspaceManifest),
    Package(PackageManifest),
}

// a way to represent the kind of manifest we parsed, without
// all the `Option`s :)
enum ManifestKind {
    VirtualWorkspace {...},
    Workspace {...},
    Package {...},
}

struct UncheckedManifest { 
    parsed_toml: ParsedToml,
    // potentially other things? 
}

struct ParsedToml {
    /// Top-level TOML "tables" started by `[headers]` alongside 
    /// their defined key-value pairs.
    tables: Vec<ManifestTable>,
    
    // ...(other fields if needed)
}

impl ParsedToml {
    type Document = toml_edit::ImDocument<String>;

    pub fn new(document: Document) -> Self {
        // parse the toml into tables? i wouldn't keep it as an ImDocument
        Self { ... }
    }
}

impl UncheckedManifest {
    pub fn new(parsed_toml: ParsedToml) -> Self {
        Self { ... }
    }

    // some first step. starts the chain
    pub fn make_first_step(self) -> CargoResult<FirstStepManifest> {
        // operations to make the first step
        FirstStepManifest::new(self)
    }

    /// Builds the Manifest through several waves of check/construction steps.
    pub fn build(self) -> CargoResult<ParsedManifest> {
        self.make_first_step()?
           .other_ops()? // ...
           .check_validity()?
           .check_dependencies()?
           .other_ops()? // ...
           .finish() // creates the ParsedManifest from the data we've gathered
   }
}

// ...


struct ManifestValidity { 
    // ...fields from the prior step...
}

struct ManifestDependencies { 
    // ...fields from the prior step...
}

// ...

impl ManifestValidity {
    pub fn check_validity(self) -> CargoResult<ManifestDependencies> {
        // run a bunch of checks
        
        // at some point, check if we have a [workspace], [package], or both!
        // (the "manifest.transpose().map(ManifestKind:: ...)" pattern)
        
        Ok(ManifestDependencies {
            // ...other fields
            manifest: ManifestKind,
        })
    }
}

impl ManifestDependencies {
   pub fn check_dependencies(self) -> CargoResult<ManifestNextStep> {
      // ...
   }
}

// ...
```

If the manual returns bother you, there are also generic versions of the pattern:

```rust
// note: you can use a trait instead. this would work fine if error states 
// don't need to build on one another.
trait Scan {
    type NextState;
    
    pub fn scan(&self) -> NextState;
}

pub fn parse_manifest<S: Scan>(document: Document) -> CargoResult<UncheckedManifest> {
    let mut step: CargoResult<Either<S, UncheckedManifest>> = ParseToml::new(document);
    loop {
        // `?` the CargoResult, then check if they returned the type we want or not.
        // consider using a functional style for this.
    }
}
```

I'm not a big fan of those, as they feel a bit like weird linked lists, but some folks seem to like them nonetheless.

## Conclusion

In any case, I'm in favor of having a state machine with unmistakable steps for Cargo's manifest parsing + analysis. It would require many changes to the codebase, but could overall help separate the manifest creation and avoid meddling across modules. 

Both points assist with error handling, as we now know enough about *where* things went wrong to give little `note` or `help` diagnostics like the compiler. It becomes much easier to specify to the user that we assumed they have a virtual workspace, as that's now a type!

Future diagnostics could be more helpful for users, maybe even reaching the ease of adding lints to something like Clippy, as it becomes much easier to detect faulty state.

Thank you for your help and attention!

**Comment by onkoe** [comment]
Ah, sorry, @epage. Just realized you likely don't watch all these issues, so here's a tag! 😄

Also, I did want to clarify a few things:

- If I misused "parse", please imagine it as something better. I didn't want to make hard suggestions as I haven't worked with this codebase long-term.
- Your ideas on organization are spot-on! I'm not quite after "clean code", though. Instead, these changes should improve accessibility for contributors. In any way that's done, I'll be happy. A 'tangible' state machine is still my preference, though, but that may prevent the "god type" you were mentioning. So... our thinking might be in line. 
- For the "optimization" part of things, I meant more streamlining the analysis process. Sorry for the confusion!

Again, thanks for your quick and detailed reply! :)

**Comment by epage** [comment]
@onkoe Overall, I feel like that would make the design more complex, with lots of types with unclear roles in the process, and this would make it harder to refactor as changes in the inputs for a part of the process could easily cause a shuffling of the stages.

This is also getting pretty far afield from the actual issue.

**Comment by joelvpayne** [comment]
> I just tried to reproduce this and didn't get any errors. Could you provide more concrete reproduction steps and use cases that lead to these mistaken workspace manifests so we can better consider how the user gets into these situations so we understand what errors to look at and how to improve them?

I reproduced this error by accident and can share how it happened for me.

I was using vscode, using Bash terminal inside vscode, and somehow ended up overwriting or deleting part of my Cargo.toml file. 

The messed up Cargo.toml file did not list the rand crate under dependencies, but main was trying to use rand. 

Not sure if this helps, but found this comment while trying to solve my error code.

**Comment by madhav-madhusoodanan** [comment]
Hi, is this still being worked on? 
I'd love to work on this if we still need assistance for this issue.
