### ISSUE TITLE
arithmetic operation overflowed

### ISSUE THREAD

**Issue by adjivas** [rust-lang/cargo#2033]
I tried this toml:
```cargo
[package]
name = "game"
version = "0.1.0"
authors = ["adjivas <adjivas@users.noreply.github.com>"]

[dependencies]
piston_window = "0.15.0"

[target.x86_64-apple-darwin.freetype]
native = {
  libs: ["freetype"],
  link_paths: ["/Volumes/Data/nfs/zfs-student-5/users/2013/adjivas/.brew/Cellar/freetype/2.6_1/lib"],
  frameworks: [],
  framework_paths: [],
  include_paths: ["/Volumes/Data/nfs/zfs-student-5/users/2013/adjivas/.brew/Cellar/freetype/2.6_1/include/freetype2"],
  version: "18.0.12"
}
rustc-link-search = ["native=/Volumes/Data/nfs/zfs-student-5/users/2013/adjivas/.brew/Cellar/freetype/2.6_1/lib"]
rustc-link-lib = ["freetype"]
```
I expected to see this happen:
```shell
$ cargo build
thread '<unnamed>' panicked at 'arithmetic operation overflowed', /private/tmp/rust20151007-99953-1hnrzb3/rustc-1.3.0/.brew_home/.cargo/registry/src/github.com-0a35038f75765ae4/toml-0.1.22/src/parser.rs:152
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Any', src/libcore/result.rs:732
 adjivas@e2r3p20:~/Project/game/ 𝄞 mkdir .rust/lib/x86_64-apple-darwin
mkdir: .rust/lib: No such file or directory
```

**Comment by alexcrichton** [comment]
Thanks for the report! Looks like this was already fixed in https://github.com/alexcrichton/toml-rs/commit/64ae43a386155b905fd4938ec40a61f3edff1856, so just need to update the version of toml we're using!
