### ISSUE TITLE
cargo run tries to execute .so named file

### ISSUE THREAD

**Issue by zazdxscf** [rust-lang/cargo#2124]
```bash
$ cargo run -v
!! executing '/home/zazdxscf/build/1nonpkgs/cargo/cargo//target/x86_64-unknown-linux-gnu/release//cargo'
   Compiling hello_world v0.0.1 (file:///tmp/a)
     Running `rustc src/main.rs --crate-name hello_world --crate-type bin -g --out-dir /tmp/a/target/debug --emit=dep-info,link -L dependency=/tmp/a/target/debug -L dependency=/tmp/a/target/debug/deps`
!! executing '/home/zazdxscf/build/1nonpkgs/rust/rust//x86_64-unknown-linux-gnu/stage2/bin//rustc'
the binaries: ["/tmp/a/target/debug/hello_world.so"]
the exe: "/tmp/a/target/debug/hello_world.so"
     Running `target/debug/hello_world.so`
Could not execute process `target/debug/hello_world.so` (never executed)

Caused by:
  No such file or directory (os error 2)
-----------
zazdxscf@gobaby 2015/11/08 00:39:42 -bash4.3.42 t:2 j:0 d:5 pp:9419 p:27302
!16288 10 101  4.2.5-hardened-r1-g45b4b78 #1 SMP Thu Nov 5 04:21:39 CET 2015
/tmp/a
/tmp/a $ cargo -Vv
!! executing '/home/zazdxscf/build/1nonpkgs/cargo/cargo//target/x86_64-unknown-linux-gnu/release//cargo'
cargo 0.7.0 (b01770c 2015-11-05)

$ rustc -Vv
!! executing '/home/zazdxscf/build/1nonpkgs/rust/rust//x86_64-unknown-linux-gnu/stage2/bin//rustc'
rustc 1.6.0-dev (bb9b5f5ed 2015-11-07)
binary: rustc
commit-hash: bb9b5f5edeb91fa7fc9bd7c220d69985e0175ba2
commit-date: 2015-11-07
host: x86_64-unknown-linux-gnu
release: 1.6.0-dev

```

actual exe:
```
$ target/debug/hello_world
Hello, world!
```

This is as far as I could get (since my rust knowledge is still at Getting Started section in the rustbook):

```
    let compile = try!(ops::compile(manifest_path, options));                   
    println!("the binaries: {:?}",compile.binaries);
    let exe = &compile.binaries[0];
    println!("the exe: {:?}",exe);
```

which is located here: https://github.com/rust-lang/cargo/commit/0d9eac6e8ff6da0e3c8d49e8b29a9cad3b325851/src/cargo/ops/cargo_run.rs#diff-96904ae2ae6c898611cd71d0427b25a3L46

I'll try reverting that next, after `make test` completes
**EDIT:** I can't cleanly revert that commit, so I didn't try without it.
**EDIT2:** reverting only the visible differences in the above link, makes no difference! (tested) also it takes 9minutes to recompile if any change is made in that file :disappointed:

**Comment by zazdxscf** [comment]
Nevermind, turns out it was my own fault for using a script named `rustc` in PATH that was `exec`-uting the real `rustc`, but it was first outputing to `stdout` (instead of `stderr` which seems to work ok around this issue) the following:
`!! executing '/home/zazdxscf/build/1nonpkgs/cargo/cargo//target/x86_64-unknown-linux-gnu/release//cargo'`

and this is what caused `cargo run -v` to try to execute the `.so` named file. Odd.

I know this because I also tried adding the args to the stdout output and it ICE-d this time:
```bash
$ cargo build -v
!! executing '/home/zazdxscf/build/1nonpkgs/cargo/cargo//target/x86_64-unknown-linux-gnu/release//cargo' with args: 'build -v'
thread '<main>' panicked at 'rustc --print-file-name output has changed', src/cargo/ops/cargo_rustc/context.rs:125
stack backtrace:
   1:       0x14338962d6 - sys::backtrace::tracing::imp::write::h08acc3b033087536ZEt
                        at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:40
   2:       0x143389d45c - panicking::log_panic::h124910731bd8b28aNCx
                        at src/libstd/panicking.rs:48
                        at src/libstd/panicking.rs:61
   3:       0x143386ffa3 - sys_common::unwind::begin_unwind_inner::h506b06b04dbe57654xs
                        at src/libstd/panicking.rs:87
                        at src/libstd/sys/common/unwind/mod.rs:249
   4:       0x14334b92ef - sys_common::unwind::begin_unwind::begin_unwind::h6454675875015295555
   5:       0x14335a250c - ops::cargo_rustc::context::_<impl>::filename_parts::h8d1713a15c07b349P3k
   6:       0x143351552e - ops::cargo_rustc::context::_<impl>::new::h4c2746bbdacbf681P0k
   7:       0x1433529781 - ops::cargo_rustc::compile_targets::ha3d2831549c7f7a76lo
   8:       0x14335208f1 - ops::cargo_compile::compile_pkg::h04f3f89a0d04c977tSh
   9:       0x143351cc10 - ops::cargo_compile::compile::h71b9af729cca8401pLh
  10:       0x1433440bf0 - call_main_without_stdin::call_main_without_stdin::h15506494176407654045
  11:       0x143342b7fb - execute::h4ac484f0ea0a36ca5ca
  12:       0x1433428284 - call_main_without_stdin::call_main_without_stdin::h17109097588534179162
  13:       0x1433425072 - main::h22e5c5a87fc52ad0Tca
  14:       0x143389cc19 - sys_common::unwind::try::try_fn::h11032567466427723308
                        at src/libstd/thread/mod.rs:381
                        at src/libstd/sys/common/unwind/mod.rs:163
  15:       0x14338956a8 - __rust_try
  16:       0x143389ca1a - rt::lang_start::hf5c789a2a64a3706Vzx
                        at src/libstd/sys/common/unwind/mod.rs:151
                        at src/libstd/thread/local.rs:217
                        at src/libstd/sys/common/unwind/mod.rs:148
                        at src/libstd/sys/common/unwind/mod.rs:133
                        at src/libstd/thread/mod.rs:381
                        at src/libstd/rt.rs:60
  17:      0x354f23b16a3 - __libc_start_main
                        at /usr/src/debug/sys-libs/glibc-2.22-r1/glibc-2.22/csu/libc-start.c:289
  18:       0x1433424958 - _start
                        at ../sysdeps/x86_64/start.S:108
  19:                0x0 - <unknown>

```


So interestingly odd...
I guess, cargo somehow uses the stdout for something, and gets it confused enough to cause this issue or the above ICE.

Anyway, apologies for the noise.
