### ISSUE TITLE
The filename or extension is too long when downloading dependencies on windows

### ISSUE THREAD

**Issue by andruhon** [rust-lang/cargo#2309]
I getting following error when trying to build https://github.com/dherman/wc-demo:

```
unable to get packages from source

Caused by:
  failed to unpack package `neon-sys v0.1.7`

Caused by:
  failed to create `C:/multirust/toolchains/stable/cargo\registry\src\github.com-88ac128001ac3a9a\neon-sys-0.1.7\node_modules\node-gyp\node_modules\request\node_modules\har-validator\node_modules\is-my-json-alid\node_modules\generate-object-property\node_modules\is-property`

Caused by:
  The filename or extension is too long. (os error 206)
```

I think it is cargo's issue. However I've created an issue in wc-demo as well.
https://github.com/dherman/wc-demo/issues/5

**Comment by rask** [comment]
Ah, the ~255 path length issue again. Are you using npm? Does Cargo init the npm fetching process? Update npm to version 3+ and see whether that changes anything.

npm 2 saved `node_modules` to recursive directories, npm 3+ saves them to a single flat `node_modules` directory (which in turn could mean +80% in path length reduction regarding the worst packages).

**Comment by andruhon** [comment]
Hm... So you say it is likely to be NPM issue? I'm using NPM 3.3.12 and it seems to work fine with that deep dependencies. 
Do you think it's getting stucked somewhere here https://github.com/rustbridge/neon/blob/master/crates/neon-sys/build.rs#L21 ?

**Comment by andruhon** [comment]
Ok. It seems to be an issue in https://github.com/dherman/wc-demo/issues/5
```
...
Build failed, waiting for other jobs to finish...
failed to run custom build command for `neon-sys v0.1.7`
Process didn't exit successfully: `C:\local_projects\rust\wc-demo\native\target\debug\build\neon-sys-51e0087a6aa7f0e4\build-script-build` (exit code: 101)
--- stderr
thread '<main>' panicked at 'failed to run "npm install" for neon-sys', ../src/libcore\option.rs:335
```

**Comment by alexcrichton** [comment]
Ah yeah this is likely something that Cargo should handle (e.g. use verbatim paths), but it's also probably true that even if Cargo worked many other parts of the system would be likely to choke quickly as it's rare-ish to see support for longer path names like this.

**Comment by andruhon** [comment]
I've tried to handle the output rather than just assessing that `npm install` is not failed and figured out that rust can't find command `npm`, replacing "npm" to "npm.cmd" in build.rs helps, however it now choking on `Command::new("npm.cmd").arg("run").arg(if debug() { "build-debug" } else { "build-release" }).status().ok().unwrap();`. It seems like it can't find some `ar`

```
> @ build-debug C:\local_projects\rust\wc-demo\native\crates\neon\crates\neon-sys
> node-gyp build -d


C:\local_projects\rust\wc-demo\native\crates\neon\crates\neon-sys>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" build -d )  else (node  build -d )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  neon.cc
  win_delay_load_hook.c
  neon.vcxproj -> C:\local_projects\rust\wc-demo\native\crates\neon\crates\neon-sys\build\Debug\\neon.node
npm done
TARGET = Some("x86_64-pc-windows-gnu")
TARGET = Some("x86_64-pc-windows-gnu")
HOST = Some("x86_64-pc-windows-gnu")
AR_x86_64-pc-windows-gnu = None
AR_x86_64_pc_windows_gnu = None
HOST_AR = None
AR = None
TARGET = Some("x86_64-pc-windows-gnu")
running: "ar" "crus" "C:\\local_projects\\rust\\wc-demo\\native\\crates\\neon\\crates\\neon-sys\\target\\debug\\build\\neon-sys-0c837cef5759fa85\\out\\libneon.a" "build/Debug/obj.target/neon/src/neon.o"


failed to execute command: The system cannot find the file specified. (os error 2)
Is `ar` not installed? (see https://github.com/alexcrichton/gcc-rs#compile-time-requirements for help)



--- stderr
npm WARN EPACKAGEJSON neon-sys No description
npm WARN EPACKAGEJSON neon-sys No repository field.
npm WARN EPACKAGEJSON neon-sys No license field.
thread '<main>' panicked at 'explicit panic', C:\multirust\cargo\registry\src\github.com-88ac128001ac3a9a\gcc-0.3.21\src\lib.rs:772
```

(I'm not sure now how did I get the original "file too long" message)

**Comment by andruhon** [comment]
Installed gcc for msys2 via packman, now having this:

```
...
C:\local_projects\rust\wc-demo\native\crates\neon\crates\neon-sys>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" build -d )  else (node  build -d )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  neon.cc
  win_delay_load_hook.c
  neon.vcxproj -> C:\local_projects\rust\wc-demo\native\crates\neon\crates\neon-sys\build\Debug\\neon.node
npm done
TARGET = Some("x86_64-pc-windows-gnu")
TARGET = Some("x86_64-pc-windows-gnu")
HOST = Some("x86_64-pc-windows-gnu")
AR_x86_64-pc-windows-gnu = None
AR_x86_64_pc_windows_gnu = None
HOST_AR = None
AR = None
TARGET = Some("x86_64-pc-windows-gnu")
running: "ar" "crus" "C:\\local_projects\\rust\\wc-demo\\native\\crates\\neon\\crates\\neon-sys\\target\\debug\\build\\neon-sys-0c837cef5759fa85\\out\\libneon.a" "build/Debug/obj.target/neon/src/neon.o"
ExitStatus(ExitStatus(1))


command did not execute successfully, got: exit code: 1



--- stderr
npm WARN EPACKAGEJSON neon-sys No description
npm WARN EPACKAGEJSON neon-sys No repository field.
npm WARN EPACKAGEJSON neon-sys No license field.
ar: build/Debug/obj.target/neon/src/neon.o: No such file or directory
thread '<main>' panicked at 'explicit panic', C:\multirust\cargo\registry\src\github.com-88ac128001ac3a9a\gcc-0.3.21\src\lib.rs:772
```

Will try to compile with msvc toolchain...

**Comment by andruhon** [comment]
It seems like it is not a cargo issue.
