### ISSUE TITLE
Cargo should report the name of the test that failed.

### ISSUE THREAD

**Issue by brson** [rust-lang/cargo#2529]
When a test fails in cargo it prints

```
thread 'delete_data' panicked at 'ok ["rustup", "self", "delete-data", "-y"]', src/multirust-mock/src/clitools.rs:175


failures:
    delete_data
    list_targets

test result: FAILED. 10 passed; 2 failed; 0 ignored; 0 measured

error: test failed
```

At this stage I want to narrow down the test run to troubleshoot, which means running `cargo test --test $sometest`. Unfortunately figuring out the value of `$sometest` requires me to backscroll until I find this line:

```
     Running target/debug/cli_exact-b2b7a3593070551d
```

Instead I would like cargo to finish the build with something like

```
error: test 'cli-exact' failed
```

**Comment by srinivasreddy** [comment]
I want to take this.

**Comment by brson** [comment]
@srinivasreddy Go for it!

**Comment by srinivasreddy** [comment]
@brson  isn't  the rust reporting that now? Please see this output.
```
diff --git a/tests/resolve.rs b/tests/resolve.rs
index 933996a..12e7ce9 100644
--- a/tests/resolve.rs
+++ b/tests/resolve.rs
@@ -374,3 +374,7 @@ fn hard_equality() {
                                        ("foo", "1.0.0"),
                                        ("bar", "1.0.0")])));
 }
+#[test]
+fn hard_test() {
+assert!(1==2);
+}
srinivas@Srini:~/workspace/github/cargo/tests$ cargo test hard_test
     Running /home/srinivas/workspace/github/cargo/target/debug/cargo-2d6684c4458c6ec2

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured

     Running /home/srinivas/workspace/github/cargo/target/debug/resolve-2e478e860e67f7b6

running 1 test
test hard_test ... FAILED

failures:

---- hard_test stdout ----
	thread 'hard_test' panicked at 'assertion failed: 1 == 2', resolve.rs:379


failures:
    hard_test

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured

```
Metadata
```
srinivas@Srini:~/workspace/github/cargo/tests$ rustc --version
rustc 1.6.0 (c30b771ad 2016-01-19)
srinivas@Srini:~/workspace/github/cargo/tests$ cargo version
cargo 0.7.0-nightly (1af03be 2015-12-08)
```

**Comment by brson** [comment]
@srinivasreddy Sorry I missed your question.

It's reporting the name of the `#[test]` yes, but it's not reporting the executable that came from. There are two different test concepts here - the Rust functions that represet individual tests, and the executables Cargo builds containing such tests. Cargo also considers the latter to be tests, and those are the names passed to `cargo --test`, and those are the names Cargo doesn't print during a test failure.

**Comment by cyplo** [comment]
Hello ! Any news on this one ?:)
