### ISSUE TITLE
Large gitconfig causes cargo to be unresponsive

### ISSUE THREAD

**Issue by jquick** [rust-lang/cargo#2540]
Had some time to get into rust this weekend. Installed via:

```
curl -sSf https://static.rust-lang.org/rustup.sh | sh
```

Was going to make a simple web-server using the tiny-http cargo but I seem to have major issues with cargo. It installed fine (with rust) but every time I run any cargo command it takes up to 10 min to return. Even if its just the help command. 

Just running cargo it takes 100% of my cpu and stracing it is just doing:

```
jquick    5566  100  1.0 191708 21336 pts/2    R+   14:06   2:18 cargo   

Process 5566 attached
brk(0x7f4e14770000)                     = 0x7f4e14770000
brk(0x7f4e14791000)                     = 0x7f4e14791000
brk(0x7f4e147b2000)                     = 0x7f4e147b2000
brk(0x7f4e147d3000)                     = 0x7f4e147d3000
brk(0x7f4e147f4000)                     = 0x7f4e147f4000
brk(0x7f4e14815000)                     = 0x7f4e14815000
brk(0x7f4e14836000)                     = 0x7f4e14836000
brk(0x7f4e14857000)                     = 0x7f4e14857000
brk(0x7f4e14878000)                     = 0x7f4e14878000
brk(0x7f4e14899000)                     = 0x7f4e14899000
brk(0x7f4e148ba000)                     = 0x7f4e148ba000
brk(0x7f4e148db000)                     = 0x7f4e148db000
brk(0x7f4e148fc000)                     = 0x7f4e148fc000
brk(0x7f4e1491d000)                     = 0x7f4e1491d000
brk(0x7f4e1493e000)                     = 0x7f4e1493e000
brk(0x7f4e1495f000)                     = 0x7f4e1495f000
brk(0x7f4e14980000)                     = 0x7f4e14980000
brk(0x7f4e149a1000)                     = 0x7f4e149a1000
brk(0x7f4e149c2000)                     = 0x7f4e149c2000
brk(0x7f4e149e3000)                     = 0x7f4e149e3000
brk(0x7f4e14a04000)                     = 0x7f4e14a04000
brk(0x7f4e14a25000)                     = 0x7f4e14a25000
brk(0x7f4e14a46000)                     = 0x7f4e14a46000
```

This basically makes cargo unusable as any command like run or build takes forever. Am I missing something? (Ubuntu 14.04 up to date)

**Comment by jquick** [comment]
full strace of just cargo:
```
jquick@optimus:~
> sudo strace -p 5976
[sudo] password for jquick:
Process 5976 attached
brk(0x7f73f919f000)                     = 0x7f73f919f000
brk(0x7f73f91c0000)                     = 0x7f73f91c0000
brk(0x7f73f91e1000)                     = 0x7f73f91e1000
brk(0x7f73f9202000)                     = 0x7f73f9202000
brk(0x7f73f9223000)                     = 0x7f73f9223000
brk(0x7f73f9244000)                     = 0x7f73f9244000
brk(0x7f73f9265000)                     = 0x7f73f9265000
brk(0x7f73f9286000)                     = 0x7f73f9286000
brk(0x7f73f92a7000)                     = 0x7f73f92a7000
brk(0x7f73f92c8000)                     = 0x7f73f92c8000
brk(0x7f73f92e9000)                     = 0x7f73f92e9000
brk(0x7f73f930a000)                     = 0x7f73f930a000
brk(0x7f73f932b000)                     = 0x7f73f932b000
brk(0x7f73f934c000)                     = 0x7f73f934c000
brk(0x7f73f936d000)                     = 0x7f73f936d000
brk(0x7f73f938e000)                     = 0x7f73f938e000
brk(0x7f73f93af000)                     = 0x7f73f93af000
brk(0x7f73f93d0000)                     = 0x7f73f93d0000
brk(0x7f73f93f1000)                     = 0x7f73f93f1000
brk(0x7f73f9412000)                     = 0x7f73f9412000
brk(0x7f73f9433000)                     = 0x7f73f9433000
brk(0x7f73f9454000)                     = 0x7f73f9454000
brk(0x7f73f9475000)                     = 0x7f73f9475000
brk(0x7f73f9496000)                     = 0x7f73f9496000
brk(0x7f73f94b7000)                     = 0x7f73f94b7000
brk(0x7f73f94d8000)                     = 0x7f73f94d8000
brk(0x7f73f94f9000)                     = 0x7f73f94f9000
brk(0x7f73f951a000)                     = 0x7f73f951a000
brk(0x7f73f953b000)                     = 0x7f73f953b000
brk(0x7f73f955c000)                     = 0x7f73f955c000
brk(0x7f73f957d000)                     = 0x7f73f957d000
brk(0x7f73f959e000)                     = 0x7f73f959e000
brk(0x7f73f95bf000)                     = 0x7f73f95bf000
brk(0x7f73f95e0000)                     = 0x7f73f95e0000
brk(0x7f73f9601000)                     = 0x7f73f9601000
brk(0x7f73f9622000)                     = 0x7f73f9622000
brk(0x7f73f9643000)                     = 0x7f73f9643000
brk(0x7f73f9664000)                     = 0x7f73f9664000
brk(0x7f73f9685000)                     = 0x7f73f9685000
brk(0x7f73f96a6000)                     = 0x7f73f96a6000
brk(0x7f73f96c7000)                     = 0x7f73f96c7000
brk(0x7f73f96e8000)                     = 0x7f73f96e8000
brk(0x7f73f9709000)                     = 0x7f73f9709000
brk(0x7f73f972a000)                     = 0x7f73f972a000
brk(0x7f73f974b000)                     = 0x7f73f974b000
brk(0x7f73f976c000)                     = 0x7f73f976c000
brk(0x7f73f978d000)                     = 0x7f73f978d000
brk(0x7f73f97ae000)                     = 0x7f73f97ae000
brk(0x7f73f97cf000)                     = 0x7f73f97cf000
brk(0x7f73f97f0000)                     = 0x7f73f97f0000
brk(0x7f73f9811000)                     = 0x7f73f9811000
munmap(0x7f73f6da6000, 1003520)         = 0
access("/home/jquick/.config/git/config", F_OK) = -1 ENOENT (No such file or directory)
access("/etc/gitconfig", F_OK)          = -1 ENOENT (No such file or directory)
madvise(0x7f73f4889000, 4096, MADV_DONTNEED) = 0
madvise(0x7f73f489f000, 4096, MADV_DONTNEED) = 0
madvise(0x7f73f485f000, 28672, MADV_DONTNEED) = 0
madvise(0x7f73f489f000, 4096, MADV_DONTNEED) = 0
madvise(0x7f73f488a000, 53248, MADV_DONTNEED) = 0
madvise(0x7f73f4858000, 28672, MADV_DONTNEED) = 0
madvise(0x7f73f488a000, 36864, MADV_DONTNEED) = 0
write(1, "\33(B\33[0mRust's package manager\n\nU"..., 945) = 945
write(1, "See 'cargo help <command>' for m"..., 71) = 71
write(1, "\33(B\33[0m", 7)              = 7
munmap(0x7f73f6ea9000, 8192)            = 0
exit_group(0)                           = ?
+++ exited with 0 +++

```

The command finishes fine it just takes forever due to the memory brk stuff.

**Comment by jquick** [comment]
```
> rustc -V
rustc 1.7.0 (a5d1e7a59 2016-02-29)
jquick@optimus:~
> cargo -V
cargo 0.8.0-nightly (28a0cbb 2016-01-17)
```

**Comment by alexcrichton** [comment]
I think that this may have been fixed on nightly recently actually, can you try out with nightly Cargo and see if it works?

**Comment by alexcrichton** [comment]
Hm also, can you try to get a backtrace of Cargo when it appears to be hanging?

**Comment by jquick** [comment]
Tried the nightly rust via:
```
> ./rustup.sh --uninstall
> ./rustup.sh -s -- --channel=beta
```
```
jquick@optimus:~
> cargo -V
cargo 0.9.0-nightly (8fc3fd8 2016-02-29)
```
Same issue unfortunately. Not exactly sure how to attach to a process and dump a stack but i googled around and did some gdb stuff:

```
jquick@optimus:~/dev/polycom_caller
> sudo gcore 31759
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007f30b74a8676 in read_on_variable ()
warning: Memory read failed for corefile section, 8192 bytes at 0x7ffe6e3b7000.
Saved corefile core.31759
jquick@optimus:~/dev/polycom_caller
> gdb cargo core.31759
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from cargo...done.
[New LWP 31759]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `cargo'.
#0  0x00007f30b74a8676 in read_on_variable ()
(gdb) bt
#0  0x00007f30b74a8676 in read_on_variable ()
#1  0x00007f30b74a613b in config_parse ()
#2  0x00007f30b74a66e4 in config_open ()
#3  0x00007f30b748e0e2 in git_config_add_backend ()
#4  0x00007f30b748e31b in git_config_add_file_ondisk ()
#5  0x00007f30b748eb20 in git_config_open_default ()
#6  0x00007f30b739a4c7 in config::Config::open_default::hdded9abf3804e1499Wd ()
#7  0x00007f30b72cceb9 in ops::registry::http_proxy::h8b31791c3e7c18390xq ()
#8  0x00007f30b72cd2bb in ops::registry::http_proxy_exists::h89f08ee29890302c9yq ()
#9  0x00007f30b70f767a in execute::h38ff5dff31c326besMc ()
#10 0x00007f30b70f4d45 in call_main_without_stdin::h8976079778260793956 ()
#11 0x00007f30b70f1dcb in main::h5458bbdcd8f4a2307ca ()
#12 0x00007f30b764ca25 in sys_common::unwind::try::try_fn::h9504535173218613138 ()
#13 0x00007f30b76443fc in __rust_try ()
#14 0x00007f30b764c4af in rt::lang_start::h86595346586db82djRy ()
#15 0x00007f30b6229ec5 in __libc_start_main () from /lib/x86_64-linux-gnu/libc.so.6
#16 0x00007f30b70f1729 in _start ()
```

**Comment by jquick** [comment]
Sorry, I realized I was using beta instead of nightly. Using the nightly fixed the memory issues but still was taking 12 seconds to return the cargo version. Much faster but still weird imo. Stracing again it looks like all the time was eating up by:
```
10:25:17 mmap(NULL, 2097152, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fa66d600000
10:25:18 mmap(NULL, 2097152, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fa66d400000
10:25:21 mmap(NULL, 2097152, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fa66d200000
10:25:25 mmap(NULL, 2097152, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fa66d000000
```
https://gist.github.com/5a146b2171462c01f502b5ea7be61dc3 - If this is normal then we can close this just not sure what the expected behavior is. Here is the trace from the slow parst:

```
(gdb) bt
#0  0x00007fa76f36b9b6 in read_on_variable ()
#1  0x00007fa76f36947b in config_parse ()
#2  0x00007fa76f369a24 in config_open ()
#3  0x00007fa76f351422 in git_config_add_backend ()
#4  0x00007fa76f35165b in git_config_add_file_ondisk ()
#5  0x00007fa76f351e60 in git_config_open_default ()
#6  0x00007fa76f300137 in git2::config::Config::open_default::h01710fe6e7f00c85 ()
#7  0x00007fa76f162f29 in cargo::ops::registry::http_proxy::hbe82ed28752ced73 ()
#8  0x00007fa76f16332b in cargo::ops::registry::http_proxy_exists::h295d89b60dac4386 ()
#9  0x00007fa76ef82e74 in cargo::execute::hab577e023b3ac5e2 ()
#10 0x00007fa76ef80744 in cargo::call_main_without_stdin::hf709651485746f28 ()
#11 0x00007fa76ef7d8a2 in cargo::main::h2b219a79f378c1ef ()
#12 0x00007fa76f530d55 in std::sys_common::unwind::try::try_fn::h512e768250918f40 ()
#13 0x00007fa76f52763c in __rust_try ()
#14 0x00007fa76f53079c in std::rt::lang_start::h2dd73040e4b52b40 ()
#15 0x00007fa76e2cdec5 in __libc_start_main () from /lib/x86_64-linux-gnu/libc.so.6
#16 0x00007fa76ef7d229 in _start ()
```

**Comment by alexcrichton** [comment]
Hm it looks like libgit2 may be for some reason taking a very long time to read your git configuration. Do you have anything nonstandard perhaps about your git configuration?

**Comment by jquick** [comment]
Welp, reinstalled git via apt-get but that didn't help. Started looking around at the config files. For some reason my .gitconfig had 20k lines of UI=true. removing that fixed all the cargo issues. Thanks Alex for the help and sorry for the wild goose chase.

**Comment by alexcrichton** [comment]
I've submitted an [upstream bug report](https://github.com/libgit2/libgit2/issues/3725)

**Comment by Eh2406** [comment]
Looks like we have a workaround, and the root bug won't be fixed. So I am going to close for now. If you think it should still be open feel free to comment and I will fix it.
