### ISSUE TITLE
cargo test does not give file name for panics in macros

### ISSUE THREAD

**Issue by jonhoo** [rust-lang/cargo#2581]
**Description**:
If a test case fails with a panic inside of a macro invocation, the test file name is not included in the stack trace.

**Steps to reproduce**:
```console
$ cargo new test-macro-panic
$ cd test-macro-panic
$ $EDITOR src/lib.rs
```
```rust
// src/lib.rs
#[cfg(test)]
mod tests {
    #[test]
    fn it_works() {
        use std::collections::HashMap;
        let x: HashMap<&str, &str> = HashMap::new();
        assert_eq!(x["y"], "z");
    }
}
```

**Actual output**:
```console
$ cargo test
   Compiling macro-hiding v0.1.0 (file:///tmp/test-macro-panic)
     Running target/debug/test-macro-panic-1d0aa276665db59b

running 1 test
test tests::it_works ... FAILED

failures:

---- tests::it_works stdout ----
	thread 'tests::it_works' panicked at 'no entry found for key', ../src/libcore/option.rs:704
stack backtrace:
   1:     0x55a4eb5b84a0 - sys::backtrace::tracing::imp::write::h3675b4f0ca767761Xcv
   2:     0x55a4eb5bae5b - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44519
   3:     0x55a4eb5baa13 - panicking::default_handler::h18faf4fbd296d909lSz
   4:     0x55a4eb5aebec - sys_common::unwind::begin_unwind_inner::hfb5d07d6e405c6bbg1t
   5:     0x55a4eb5af038 - sys_common::unwind::begin_unwind_fmt::h8b491a76ae84af35m0t
   6:     0x55a4eb5b7911 - rust_begin_unwind
   7:     0x55a4eb5ea3ef - panicking::panic_fmt::h98b8cbb286f5298alcM
   8:     0x55a4eb5eedd4 - option::expect_failed::ha2bedd125befb493uGO
   9:     0x55a4eb56fcdf - option::Option<T>::expect::h665506949329256301
                        at ../src/libcore/option.rs:298
  10:     0x55a4eb56fc7f - collections::hash::map::HashMap<K, V, S>.Index<&'a Q>::index::h10240939780779725218
                        at ../src/libstd/collections/hash/map.rs:1315
  11:     0x55a4eb56de4b - tests::it_works::h6327751ca14abcfdgaa
                        at /tmp/test-macro-panic/<std macros>:7
  12:     0x55a4eb591db6 - boxed::F.FnBox<A>::call_box::h12974170719861018744
  13:     0x55a4eb5944ab - sys_common::unwind::try::try_fn::h16547832986514587285
  14:     0x55a4eb5b789b - __rust_try
  15:     0x55a4eb5b506d - sys_common::unwind::inner_try::hadd81c754a64f07ciYt
  16:     0x55a4eb59482a - boxed::F.FnBox<A>::call_box::h8956144540797489804
  17:     0x55a4eb5b9909 - sys::thread::Thread::new::thread_start::h9bc812305b5e01feFPy
  18:     0x7f3f40fc0423 - start_thread
  19:     0x7f3f40ae9cbc - clone
  20:                0x0 - <unknown>


failures:
    tests::it_works

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured
```
Notice that backtrace segment number 11 says that the error occurred in `test-macro-panic/<std macros>:7`.

**Expected output**:
```
…
  11:     0x55a4eb56de4b - tests::it_works::h6327751ca14abcfdgaa
                        at /tmp/test-macro-panic/src/lib.rs:7
…
```

**Comment by alexcrichton** [comment]
Thanks for the report! This actually has to do with the test harness rather than Cargo itself, so could you open up a bug on rust-lang/rust instead?

**Comment by jonhoo** [comment]
Sure. Filed as rust-lang/rust/issues#32981.
