### ISSUE TITLE
`cargo test --doc` can't find crate in dev-dependencies

### ISSUE THREAD

**Issue by fengcen** [rust-lang/cargo#3422]
It works when the crate is in the `[dependencies]` section.

Rust version: 1.15.0-nightly (8f02c429a 2016-12-15)
Cargo version: 0.16.0-nightly (ddb5c32 2016-12-16)
Platform: Windows

Output:
```
running 1 test
test _0 ... FAILED

failures:

---- _0 stdout ----
        error[E0463]: can't find crate for `num_cpus`
 --> <anon>:2:1
  |
2 | extern crate num_cpus;
  | ^^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error

thread '_0' panicked at 'Box<Any>', C:\bot\slave\nightly-dist-rustc-win-msvc-64\build\src\librustc_errors\lib.rs:460
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread '_0' panicked at 'couldn't compile the test', C:\bot\slave\nightly-dist-rustc-win-msvc-64\build\src\librustdoc\test.rs:261


failures:
    _0

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured
```

Doc:
```
//! # Examples
//!
//! ```
//! extern crate num_cpus;
//!
//! fn main() {
//!     ...
//! }
//! ```
```
Cargo.toml:
```
[dev-dependencies]
num_cpus = "^1.2"
```

**Comment by alexd2580** [comment]
I have similar symptoms with the following:
Linux
rustc 1.15.0-nightly (8f02c429a 2016-12-15)
cargo 0.16.0-nightly (ddb5c32 2016-12-16)

lib.rs:
```
//! ```
//! extern crate rand;
//! # fn main() {
//! use rand::random;
//! let r = random::<u32>();
//! # }
//! ```
```

Cargo.toml:
```
[dependencies]

[dev-dependencies]
rand = "0.3.14"
```

Running `cargo test` runs the doc-test just fine, while `cargo test --doc`, which should only run the doctests, complains:
```
---- _0 stdout ----
	error[E0432]: unresolved import `rand::random`
 --> <anon>:3:5
  |
3 | use rand::random;
  |     ^^^^^^^^^^^^ no `random` in the root

error: use of unstable library feature 'rand': use `rand` from crates.io (see issue #27703)
 --> <anon>:1:1
  |
1 | extern crate rand;
  | ^^^^^^^^^^^^^^^^^^
  |
  = help: add #![feature(rand)] to the crate attributes to enable
```

Executing both commands with `--verbose` yields:
`cargo test --verbose`:
```
   Doc-tests testdep
     Running `rustdoc --test /home/sascha/testdep/src/lib.rs --crate-name testdep -L dependency=/home/sascha/testdep/target/debug/deps --extern testdep=/home/sascha/testdep/target/debug/deps/libtestdep-3c91bddf1516a6f6.rlib --extern rand=/home/sascha/testdep/target/debug/deps/librand-26cfd8d095643d5f.rlib`
```

And `cargo test --doc --verbose`:
```
   Doc-tests testdep
     Running `rustdoc --test /home/sascha/testdep/src/lib.rs --crate-name testdep -L dependency=/home/sascha/testdep/target/debug/deps --extern testdep=/home/sascha/testdep/target/debug/deps/libtestdep-3c91bddf1516a6f6.rlib`
```

It's not related to using the `rand` crate, when other crates are used (tested with `nalgebra`) exclusively in doctests (being declared in the `[dev-dependencies]` section) the same behavior occurs -> the .rlib is not included when running <i>only</i> the doctests.
