### ISSUE TITLE
Create resolution errors during doc testing

### ISSUE THREAD

**Issue by brson** [rust-lang/cargo#3471]
Here's a log I saw recently while using a shared target directory. During `cargo test` doc testing the crate doesn't resolve because of dupes. Presumably cargo is not threading the proper crate resolution info through to rustdoc.

```
boom! testing assert_cli-0.3.0 against beta for full
boom! running: cargo +beta build --frozen
boom! creating container for: cargo +beta build --frozen
boom! running `docker create -v /home/ec2-user/cargobomb/./work/local/test-source/full/beta:/source:ro -v /home/ec2-user/cargobomb/./work/local/cargo-home:/cargo-home:ro -v /home/ec2-user/cargobomb/./work/local/rustup-home:/rustup-home:ro -v /home/ec2-user/cargobomb/./work/local/target-dirs/full/beta:/target:rw -e USER_ID=500 -e CMD=cargo +beta build --frozen cargobomb`
blam! 0fe8f73b578fed76fa211c200b657d773ec4b4c0fa96ae6232c66c20e0ef0e5b
boom! running `docker start -a 0fe8f73b578fed76fa211c200b657d773ec4b4c0fa96ae6232c66c20e0ef0e5b`
kablam!    Compiling assert_cli v0.3.0 (file:///source)
kablam!     Finished debug [unoptimized + debuginfo] target(s) in 1.9 secs
boom! running `docker rm -f 0fe8f73b578fed76fa211c200b657d773ec4b4c0fa96ae6232c66c20e0ef0e5b`
blam! 0fe8f73b578fed76fa211c200b657d773ec4b4c0fa96ae6232c66c20e0ef0e5b
boom! running: cargo +beta test --frozen --no-run
boom! creating container for: cargo +beta test --frozen --no-run
boom! running `docker create -v /home/ec2-user/cargobomb/./work/local/test-source/full/beta:/source:ro -v /home/ec2-user/cargobomb/./work/local/cargo-home:/cargo-home:ro -v /home/ec2-user/cargobomb/./work/local/rustup-home:/rustup-home:ro -v /home/ec2-user/cargobomb/./work/local/target-dirs/full/beta:/target:rw -e USER_ID=500 -e CMD=cargo +beta test --frozen --no-run cargobomb`
blam! b36756d09311642019e05640d82eb4248573411b311dfe1240b24e37fe6bee35
boom! running `docker start -a b36756d09311642019e05640d82eb4248573411b311dfe1240b24e37fe6bee35`
kablam!    Compiling assert_cli v0.3.0 (file:///source)
kablam!     Finished debug [unoptimized + debuginfo] target(s) in 1.15 secs
boom! running `docker rm -f b36756d09311642019e05640d82eb4248573411b311dfe1240b24e37fe6bee35`
blam! b36756d09311642019e05640d82eb4248573411b311dfe1240b24e37fe6bee35
boom! running: cargo +beta test --frozen
boom! creating container for: cargo +beta test --frozen
boom! running `docker create -v /home/ec2-user/cargobomb/./work/local/test-source/full/beta:/source:ro -v /home/ec2-user/cargobomb/./work/local/cargo-home:/cargo-home:ro -v /home/ec2-user/cargobomb/./work/local/rustup-home:/rustup-home:ro -v /home/ec2-user/cargobomb/./work/local/target-dirs/full/beta:/target:rw -e USER_ID=500 -e CMD=cargo +beta test --frozen cargobomb`
blam! 8429dbc030cf9212ff6f69406233563bde9d52cf5687013d6e4230037dfff24e
boom! running `docker start -a 8429dbc030cf9212ff6f69406233563bde9d52cf5687013d6e4230037dfff24e`
kablam!     Finished debug [unoptimized + debuginfo] target(s) in 0.0 secs
kablam!      Running /target/debug/deps/assert_cli-b7e0d075b48968b3
blam! 
blam! running 2 tests
blam! test diff::tests::multiline_diff ... ok
kablam!      Running /target/debug/deps/macro-a36224cec7ad88ea
blam! test diff::tests::basic_diff ... ok
blam! 
blam! test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured
blam! 
blam! 
blam! running 2 tests
blam! test assert_success ... ok
blam! test assert_failure ... ok
blam! 
blam! test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured
blam! 
kablam!      Running /target/debug/deps/skeptic-02aa9d26486dd3af
blam! 
blam! running 5 tests
blam! test readme_1 ... ignored
kablam! error[E0464]: multiple matching crates for `assert_cli`
kablam!  --> /tmp/rust-skeptic.7PqGEYPCV9mC/test.rs:1:1
kablam!   |
kablam! 1 | extern crate assert_cli;
kablam!   | ^^^^^^^^^^^^^^^^^^^^^^^^
kablam!   |
kablam!   = note: candidates:
kablam!   = note: path: /target/debug/deps/libassert_cli-aac975f2a580bd20.rlib
kablam!   = note: crate name: assert_cli
kablam!   = note: path: /target/debug/deps/libassert_cli-e86ddad3439135f9.rlib
kablam!   = note: crate name: assert_cli
kablam! 
kablam! error[E0463]: can't find crate for `assert_cli`
kablam!  --> /tmp/rust-skeptic.7PqGEYPCV9mC/test.rs:1:1
kablam!   |
kablam! 1 | extern crate assert_cli;
kablam!   | ^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
kablam! 
kablam! error: aborting due to 2 previous errors
kablam! 
blam! test readme_2 ... ok
kablam! error[E0464]: multiple matching crates for `assert_cli`
kablam!  --> /tmp/rust-skeptic.pA0picbUrJos/test.rs:1:1
kablam!   |
kablam! 1 | extern crate assert_cli;
kablam!   | ^^^^^^^^^^^^^^^^^^^^^^^^
kablam!   |
kablam!   = note: candidates:
kablam!   = note: path: /target/debug/deps/libassert_cli-aac975f2a580bd20.rlib
kablam!   = note: crate name: assert_cli
kablam!   = note: path: /target/debug/deps/libassert_cli-e86ddad3439135f9.rlib
kablam!   = note: crate name: assert_cli
kablam! 
kablam! error[E0463]: can't find crate for `assert_cli`
kablam!  --> /tmp/rust-skeptic.pA0picbUrJos/test.rs:1:1
kablam!   |
kablam! 1 | extern crate assert_cli;
kablam!   | ^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
kablam! 
kablam! error: aborting due to 2 previous errors
kablam! 
blam! test readme_0 ... FAILED
blam! test readme_4 ... FAILED
kablam! error[E0464]: multiple matching crates for `assert_cli`
kablam!  --> /tmp/rust-skeptic.uPUTT1m3W1gw/test.rs:1:14
kablam!   |
kablam! 1 | #[macro_use] extern crate assert_cli;
kablam!   |              ^^^^^^^^^^^^^^^^^^^^^^^^
kablam!   |
kablam!   = note: candidates:
kablam!   = note: path: /target/debug/deps/libassert_cli-aac975f2a580bd20.rlib
kablam!   = note: crate name: assert_cli
kablam!   = note: path: /target/debug/deps/libassert_cli-e86ddad3439135f9.rlib
kablam!   = note: crate name: assert_cli
kablam! 
kablam! error[E0463]: can't find crate for `assert_cli`
kablam!  --> /tmp/rust-skeptic.uPUTT1m3W1gw/test.rs:1:14
kablam!   |
kablam! 1 | #[macro_use] extern crate assert_cli;
kablam!   |              ^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
kablam! 
kablam! error: aborting due to 2 previous errors
kablam! 
kablam! error[E0464]: multiple matching crates for `assert_cli`
kablam!  --> /tmp/rust-skeptic.2q1Xi6TcZcaR/test.rs:1:14
kablam!   |
kablam! 1 | #[macro_use] extern crate assert_cli;
kablam!   |              ^^^^^^^^^^^^^^^^^^^^^^^^
kablam!   |
kablam!   = note: candidates:
kablam!   = note: path: /target/debug/deps/libassert_cli-aac975f2a580bd20.rlib
kablam!   = note: crate name: assert_cli
kablam!   = note: path: /target/debug/deps/libassert_cli-e86ddad3439135f9.rlib
kablam!   = note: crate name: assert_cli
kablam! 
kablam! error[E0463]: can't find crate for `assert_cli`
kablam!  --> /tmp/rust-skeptic.2q1Xi6TcZcaR/test.rs:1:14
kablam!   |
kablam! 1 | #[macro_use] extern crate assert_cli;
kablam!   |              ^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
kablam! 
kablam! error: aborting due to 2 previous errors
kablam! 
blam! test readme_3 ... FAILED
kablam! error: test failed
blam! 
blam! failures:
blam! 
blam! ---- readme_0 stdout ----
blam! 	thread 'readme_0' panicked at 'command failed', /cargo-home/registry/src/github.com-1ecc6299db9ec823/skeptic-0.5.0/lib.rs:351
blam! 
blam! ---- readme_4 stdout ----
blam! 	thread 'readme_4' panicked at 'command failed', /cargo-home/registry/src/github.com-1ecc6299db9ec823/skeptic-0.5.0/lib.rs:351
blam! 
blam! ---- readme_3 stdout ----
blam! 	thread 'readme_3' panicked at 'command failed', /cargo-home/registry/src/github.com-1ecc6299db9ec823/skeptic-0.5.0/lib.rs:351
blam! 
blam! 
blam! failures:
blam!     readme_0
blam!     readme_3
blam!     readme_4
blam! 
blam! test result: FAILED. 1 passed; 3 failed; 1 ignored; 0 measured
blam! 
boom! running `docker rm -f 8429dbc030cf9212ff6f69406233563bde9d52cf5687013d6e4230037dfff24e`
blam! 8429dbc030cf9212ff6f69406233563bde9d52cf5687013d6e4230037dfff24e
```

**Comment by brson** [comment]
Bug in rust-skeptic.
