### ISSUE TITLE
SIGSEGV with nightly version

### ISSUE THREAD

**Issue by meh** [rust-lang/cargo#3833]
Yesterday I ran a `rustup update` and cargo started crashing at an odd place, I don't remember when was the last time I ran `rustup update` but stable works properly.  I hadn't changed anything on my system before updating so I'm pretty sure it's something with cargo itself.

This is the stacktrace, which looks really odd:

```
#0  0x0000555555a7a055 in OPENSSL_ia32_cpuid ()
#1  0x00007ffff60695c3 in OPENSSL_cpuid_setup () from /usr/x86_64-pc-linux-gnu/lib/libcrypto.so.38
#2  0x00007ffff604bfb7 in _init () from /usr/x86_64-pc-linux-gnu/lib/libcrypto.so.38
#3  0x0000000000000001 in ?? ()
#4  0x00007ffff7de90ca in call_init.part () from /lib64/ld-linux-x86-64.so.2
#5  0x00007ffff7de921b in _dl_init () from /lib64/ld-linux-x86-64.so.2
#6  0x00007ffff7ddacda in _dl_start_user () from /lib64/ld-linux-x86-64.so.2
#7  0x0000000000000001 in ?? ()
#8  0x00007fffffffe2ec in ?? ()
#9  0x0000000000000000 in ?? ()
```

If it could matter, I'm running libressl instead of openssl.

**Comment by alexcrichton** [comment]
Oh dear this looks quite surprising! 

So it looks like you're using your system OpenSSL, which the bundled versions of Cargo aren't supposed to use. There's a current [bug in Cargo though](https://github.com/rust-lang/rust/pull/40507) which pulls in the system libcurl accidentally, which can transitively include the system OpenSSL.

It may be worth retrying once https://github.com/rust-lang/rust/pull/40507 is merged.

**Comment by alexcrichton** [comment]
(and the corresponding beta backport (https://github.com/rust-lang/rust/pull/40525))

**Comment by alexcrichton** [comment]
Ok, that may be related to it (no idea, really, though).

Let's wait until the linkage gets fixed and then see if it's still here.

**Comment by cyplo** [comment]
Not sure how to test this on my own so - does it work for you now ? The linked issues/PRs seem to be in already.

**Comment by carols10cents** [comment]
Closing due to inactivity and guessing that the fixes are in now, please reopen if I'm mistaken! thank you!!
