### ISSUE TITLE
Panic when trying to run cargo on nightly

### ISSUE THREAD

**Issue by raphaelcohn** [rust-lang/cargo#3834]
```bash
RUST_BACKTRACE=full /Users/XXXX/.cargo/bin/cargo --version
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:323
stack backtrace:
   0:        0x10bb5e293 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::h7b906ec435ded35c
   1:        0x10bb651b4 - std::panicking::default_hook::{{closure}}::h44d92332f38028b9
   2:        0x10bb64dcd - std::panicking::default_hook::ha8486ead32221b33
   3:        0x10bb67917 - std::panicking::rust_panic_with_hook::hdbc3bba6a9dc0bb9
   4:        0x10bb677b4 - std::panicking::begin_panic::ha249c774b9bf96e1
   5:        0x10bb67722 - std::panicking::begin_panic_fmt::ha197daaf02a649ab
   6:        0x10bb67687 - rust_begin_unwind
   7:        0x10bb8f260 - core::panicking::panic_fmt::h7414cb5ce71ea361
   8:        0x10bb8f164 - core::panicking::panic::hcbe9ad6a1a4f4afd
   9:        0x10b8ad141 - cargo::version::h514bf8eb132b821a
  10:        0x10b64e097 - cargo::execute::h818fd451708539ad
  11:        0x10b642ece - cargo::call_main_without_stdin::ha5cbac72641e15a1
  12:        0x10b64dbbf - cargo::main::hd19b6454ea1b61a0
  13:        0x10bb675e5 - std::panicking::try::do_call::h24a2756282b9a31c
  14:        0x10bb6888a - __rust_maybe_catch_panic
  15:        0x10bb67d26 - std::rt::lang_start::hd19f94db0c6a490e
```
Details: Occurs on nightly 2017-03-11 and 2017-03-08
Toolchain: `nightly-2017-03-15-x86_64-apple-darwin` installed via rustup
System: Vanilla Mac OS X El Capitan, Mac Pro Cylinder
Other:
* Running `rustc` on its own seems fine
* `cargo --help` is fine
* `cargo fetch / build` is also broken:-
```bash
RUST_BACKTRACE=full cargo fetch --verbose
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:323
stack backtrace:
   0:        0x10918a293 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::h7b906ec435ded35c
   1:        0x1091911b4 - std::panicking::default_hook::{{closure}}::h44d92332f38028b9
   2:        0x109190dcd - std::panicking::default_hook::ha8486ead32221b33
   3:        0x109193917 - std::panicking::rust_panic_with_hook::hdbc3bba6a9dc0bb9
   4:        0x1091937b4 - std::panicking::begin_panic::ha249c774b9bf96e1
   5:        0x109193722 - std::panicking::begin_panic_fmt::ha197daaf02a649ab
   6:        0x109193687 - rust_begin_unwind
   7:        0x1091bb260 - core::panicking::panic_fmt::h7414cb5ce71ea361
   8:        0x1091bb164 - core::panicking::panic::hcbe9ad6a1a4f4afd
   9:        0x108ed9141 - cargo::version::h514bf8eb132b821a
  10:        0x108e6af43 - cargo::ops::registry::http_handle::ha92c0787d2d2696d
  11:        0x108e95699 - <cargo::sources::registry::remote::RemoteRegistry<'cfg> as cargo::sources::registry::RegistryData>::update_index::h7644a3bd96fbd546
  12:        0x108e9aec7 - cargo::sources::registry::RegistrySource::do_update::hbe49ec8677ca7a66
  13:        0x108e9b116 - <cargo::sources::registry::RegistrySource<'cfg> as cargo::core::source::Source>::update::h155c3dfa80eb0bd1
  14:        0x108dd14d4 - cargo::core::registry::PackageRegistry::ensure_loaded::h9d0949f231ac02ea
  15:        0x108dd4898 - <cargo::core::registry::PackageRegistry<'cfg> as cargo::core::registry::Registry>::query::he05c003fa2821a84
  16:        0x108d80d7d - <&'a mut I as core::iter::iterator::Iterator>::next::h8789851b39966a75
  17:        0x108dc17e4 - cargo::core::resolver::activate::hd7564c2aea283b45
  18:        0x108dc3473 - cargo::core::resolver::activate_deps_loop::h59ec1a024863377d
  19:        0x108dbe95e - cargo::core::resolver::resolve::h791cba6ca2ef2759
  20:        0x108e739de - cargo::ops::resolve::resolve_with_previous::h46e790a5686b9446
  21:        0x108e727e4 - cargo::ops::resolve::resolve_with_registry::hdff79d7fe804a9a6
  22:        0x108e70df6 - cargo::ops::resolve::resolve_ws::h330cde387ac1fd21
  23:        0x108dee812 - cargo::ops::cargo_fetch::fetch::h6169073f31ed0048
  24:        0x108c876c5 - cargo::try_execute_builtin_command::h6c891951512d460a
  25:        0x108c7b027 - cargo::execute::h818fd451708539ad
  26:        0x108c6eece - cargo::call_main_without_stdin::ha5cbac72641e15a1
  27:        0x108c79bbf - cargo::main::hd19b6454ea1b61a0
  28:        0x1091935e5 - std::panicking::try::do_call::h24a2756282b9a31c
  29:        0x10919488a - __rust_maybe_catch_panic
  30:        0x109193d26 - std::rt::lang_start::hd19f94db0c6a490e
```

Rather bemused.

**Comment by raphaelcohn** [comment]
Standard out output for the second trace above was:-
```bash
    Updating git repository `https://github.com/lemonrock/libc-extra.git`
    Updating git repository `https://github.com/nix-rust/nix.git`
```

As a guess, not knowing the code as well as others, I'd say there's something going on in `cargo::version`...

**Comment by alexcrichton** [comment]
Thanks for the report! This was a recent bug should be fixed now if you update your Cargo vesion

**Comment by raphaelcohn** [comment]
Fixed
