### ISSUE TITLE
Unwrap causes build to fail

### ISSUE THREAD

**Issue by mgattozzi** [rust-lang/cargo#3846]
My builds started failing today what's weird is that it seems to be failing while downloading tokio-core, but not other codebases I have. I don't think this is related to #3833, but I'm not sure.

For reference the version of rust is:
```
rustc 1.17.0-nightly (a559452b0 2017-03-17)
```

Here's the full stack trace for reference.
```
cargo build               
 Downloading tokio-core v0.1.6
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:323
stack backtrace:
   0:     0x563790e16ac3 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::hf9ed9ccfd9f14c2b
                               at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x563790e12df4 - std::sys_common::backtrace::_print::hd8a1b72dcf3955ef
                               at /checkout/src/libstd/sys_common/backtrace.rs:71
   2:     0x563790e1e6bc - std::panicking::default_hook::{{closure}}::h5ff605bba7612658
                               at /checkout/src/libstd/sys_common/backtrace.rs:60
                               at /checkout/src/libstd/panicking.rs:355
   3:     0x563790e1e284 - std::panicking::default_hook::h9bc4f6dfee57d6bd
                               at /checkout/src/libstd/panicking.rs:371
   4:     0x563790e1eb0b - std::panicking::rust_panic_with_hook::hdc01585dc2bf7122
                               at /checkout/src/libstd/panicking.rs:549
   5:     0x563790e1e9e4 - std::panicking::begin_panic::hf84f4975d9f9b642
                               at /checkout/src/libstd/panicking.rs:511
   6:     0x563790e1e919 - std::panicking::begin_panic_fmt::hcc3f360b2ba80419
                               at /checkout/src/libstd/panicking.rs:495
   7:     0x563790e1e8a7 - rust_begin_unwind
                               at /checkout/src/libstd/panicking.rs:471
   8:     0x563790e4b01d - core::panicking::panic_fmt::h795d9a9608ddc2bb
                               at /checkout/src/libcore/panicking.rs:69
   9:     0x563790e4af54 - core::panicking::panic::hcab3e0dfa81beee9
                               at /checkout/src/libcore/panicking.rs:49
  10:     0x563790acd6de - cargo::version::haea7e89a3b191e3c
```

If this is actually tokio related I'll open up the issue there instead but since it panicked in the middle of downloading I thought it was actually a cargo issue.

**Comment by konstin** [comment]
I can reproduce this when adding e.g. `reqwest = "0.4.0"` to my cargo.toml. Everything works fine in old state, but cargo crashes after adding the dependency

**Comment by ms705** [comment]
I also encounter this issue (same nightly, Ubuntu 16.04), although in my case it happens on `cargo update`:
```
$ cargo update
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:323
stack backtrace:
   0:     0x55d09b35dac3 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::hf9ed9ccfd9f14c2b
                               at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x55d09b359df4 - std::sys_common::backtrace::_print::hd8a1b72dcf3955ef
                               at /checkout/src/libstd/sys_common/backtrace.rs:71
   2:     0x55d09b3656bc - std::panicking::default_hook::{{closure}}::h5ff605bba7612658
                               at /checkout/src/libstd/sys_common/backtrace.rs:60
                               at /checkout/src/libstd/panicking.rs:355
   3:     0x55d09b365284 - std::panicking::default_hook::h9bc4f6dfee57d6bd
                               at /checkout/src/libstd/panicking.rs:371
   4:     0x55d09b365b0b - std::panicking::rust_panic_with_hook::hdc01585dc2bf7122
                               at /checkout/src/libstd/panicking.rs:549
   5:     0x55d09b3659e4 - std::panicking::begin_panic::hf84f4975d9f9b642
                               at /checkout/src/libstd/panicking.rs:511
   6:     0x55d09b365919 - std::panicking::begin_panic_fmt::hcc3f360b2ba80419
                               at /checkout/src/libstd/panicking.rs:495
   7:     0x55d09b3658a7 - rust_begin_unwind
                               at /checkout/src/libstd/panicking.rs:471
   8:     0x55d09b39201d - core::panicking::panic_fmt::h795d9a9608ddc2bb
                               at /checkout/src/libcore/panicking.rs:69
   9:     0x55d09b391f54 - core::panicking::panic::hcab3e0dfa81beee9
```

**Comment by matklad** [comment]
Looks like a duplicate of https://github.com/rust-lang/cargo/issues/3844?

**Comment by saleemrashid** [comment]
Fixed by https://github.com/rust-lang/rust/pull/40625

**Comment by mgattozzi** [comment]
It might have been a duplicate @matklad. Either way the fix that @saleemrashid mentioned fixes my issue so I'm going to close this.
