### ISSUE TITLE
"cargo build" failed to lock Cargo.lock (os error 95)

### ISSUE THREAD

**Issue by kozo2** [rust-lang/cargo#4096]
`cargo build` failed to lock `Cargo.lock` in a supercomputer environment.

```
klogin9$ pwd
~/hello_world
klogin9$ tree
.
|-- Cargo.toml
`-- src
    `-- main.rs

1 directory, 2 files
klogin9$ cat Cargo.toml
[package]

name = "hello_world"
version = "0.0.1"
authors = [ "Your name <you@example.com>" ]
klogin9$ cat src/main.rs
fn main() {
    println!("Hello, world!");
}
klogin9$ cargo --version
cargo 0.20.0-nightly (397359840 2017-05-18)
klogin9$ RUST_LOG=debug cargo build
DEBUG:cargo::build: executing; cmd=cargo-build; args=["~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/cargo", "build"]
DEBUG:cargo::core::workspace: find_root - trying /volume1/~/Cargo.toml
DEBUG:cargo::core::workspace: find_root - trying /volume1/home/-------/Cargo.toml
DEBUG:cargo::core::workspace: find_root - trying /volume1/home/Cargo.toml
DEBUG:cargo::core::workspace: find_root - trying /volume1/Cargo.toml
DEBUG:cargo::core::workspace: find_root - trying /Cargo.toml
DEBUG:cargo::core::workspace: find_members - only me as a member
DEBUG:cargo::core::registry: load/missing  file:///volume1/~/hello_world
DEBUG:cargo::sources::config: loading: file:///volume1/~/hello_world
DEBUG:cargo::core::resolver: initial activation: hello_world v0.0.1 (file:///volume1/~/hello_world)
DEBUG:cargo: exit_with_error; err=CliError { error: Some(ChainedError { error: failed to write /volume1/~/hello_world/Cargo.lock, cause: ChainedError { error: failed to lock file: /volume1/~/hello_world/Cargo.lock, cause: Operation not supported (os error 95) } }), unknown: false, exit_code: 101 }
error: failed to write /volume1/~/hello_world/Cargo.lock

Caused by:
  failed to lock file: /volume1/~/hello_world/Cargo.lock

Caused by:
  Operation not supported (os error 95)
klogin9$
```

On the other hand, `rustc` worked well.
```
$ cd src/
$ rustc --version
rustc 1.19.0-nightly (81734e0e0 2017-05-22)
$ rustc main.rs
$ ls
main  main.rs
$ ./main
Hello, world!
$
```

Do you have any idea what `(os error 95)` means?

**Comment by alexcrichton** [comment]
It looks like this is happening during a file locking operation, and it's looking like the filesystem doesn't support this operation (which is relatively normal). The [code in question](https://github.com/rust-lang/cargo/blob/a45d4e98c446232a6f6b2edaf2503940fd716fbd/src/cargo/util/flock.rs#L279-L280) is supposed to just ignore "not supported" errors but it looks like error 95 (I think ENOTSUPP?) isn't listed there.

Would you be able to test out a change to Cargo? This may be just adding an extra clause to handle ENOTSUPP as well but I'd be curious if it works out for you.

**Comment by kozo2** [comment]
Thank you for your comment.
First I tried to build cargo on the filesystem where this error occurred.
And it failed like this.
```
klogin6$ git log -1
commit 03c0a41f97c25fc5595584bdefc38b530b4d68c3
Merge: b30694b def249f
Author: bors <bors@rust-lang.org>
Date:   Wed May 31 22:51:31 2017 +0000

    Auto merge of #4090 - jluner:master, r=alexcrichton

    Add error-chain errors.

    Fixes #4209

    Convert CargoResult, CargoError into an implementation provided by error-chain. The previous is_human machinery is mostly removed; now errors are displayed unless of the Internal kind, verbose mode will print all errors.
klogin6$ ~/.cargo/bin/cargo build
error: failed to lock file: /volume1/home/hp170219/k03536/cargo/Cargo.lock

Caused by:
  Operation not supported (os error 95)
klogin6$ ~/.cargo/bin/cargo --version
cargo 0.20.0-nightly (9fcdbb44f 2017-05-22)
```

**Comment by kozo2** [comment]
So I moved to a different filesystem on the same computer and tried `cargo build`.
And it also failed like this.
```
   Compiling pkg-config v0.3.9
   Compiling unicode-xid v0.0.4
   Compiling term v0.4.5
   Compiling lazy_static v0.2.8
   Compiling void v1.0.2
   Compiling serde v1.0.8
   Compiling bitflags v0.9.1
   Compiling strsim v0.6.0
   Compiling crossbeam v0.2.10
   Compiling gcc v0.3.49
   Compiling log v0.3.8
error: command failed: 'rustc'
info: caused by: Resource temporarily unavailable (os error 11)
error: Could not compile `libc`.
Build failed, waiting for other jobs to finish...
error: command failed: 'rustc'
info: caused by: Resource temporarily unavailable (os error 11)
error: Could not compile `dtoa`.
Build failed, waiting for other jobs to finish...
error: command failed: 'rustc'
info: caused by: Resource temporarily unavailable (os error 11)
error: Could not compile `openssl-probe`.
Build failed, waiting for other jobs to finish...
error: command failed: 'rustc'
info: caused by: Resource temporarily unavailable (os error 11)
error: command failed: 'rustc'
info: caused by: Resource temporarily unavailable (os error 11)
error: Could not compile `matches`.
Build failed, waiting for other jobs to finish...
error: Could not compile `rustc-serialize`.
Build failed, waiting for other jobs to finish...
error: command failed: 'rustc'
info: caused by: Resource temporarily unavailable (os error 11)
error: Could not compile `term`.
Build failed, waiting for other jobs to finish...
error: command failed: 'rustc'
info: caused by: Resource temporarily unavailable (os error 11)
error: Could not compile `bitflags`.
Build failed, waiting for other jobs to finish...
error: command failed: 'rustc'
info: caused by: Resource temporarily unavailable (os error 11)
error: Could not compile `crossbeam`.
Build failed, waiting for other jobs to finish...
error: command failed: 'rustc'
info: caused by: Resource temporarily unavailable (os error 11)
error: Could not compile `strsim`.
Build failed, waiting for other jobs to finish...
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 11, message: "Resource temporarily unavailable" } }', /checkout/src/libcore/result.rs:859
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: Could not compile `utf8-ranges`.
Build failed, waiting for other jobs to finish...
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 11, message: "Resource temporarily unavailable" } }', /checkout/src/libcore/result.rs:859
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 11, message: "Resource temporarily unavailable" } }', /checkout/src/libcore/result.rs:859
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: Could not compile `itoa`.
Build failed, waiting for other jobs to finish...
error: Could not compile `num-traits`.
Build failed, waiting for other jobs to finish...
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 11, message: "Resource temporarily unavailable" } }', /checkout/src/libcore/result.rs:859
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 11, message: "Resource temporarily unavailable" } }', /checkout/src/libcore/result.rs:859
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 11, message: "Resource temporarily unavailable" } }', /checkout/src/libcore/result.rs:859
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 11, message: "Resource temporarily unavailable" } }', /checkout/src/libcore/result.rs:859
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: Could not compile `gcc`.
Build failed, waiting for other jobs to finish...
error: Could not compile `pkg-config`.
Build failed, waiting for other jobs to finish...
error: Could not compile `serde`.
Build failed, waiting for other jobs to finish...
error: Could not compile `lazy_static`.
Build failed, waiting for other jobs to finish...
error: build failed
```

And `RUST_BACKTRACE=1` version is like this
```
   Compiling bitflags v0.8.2
   Compiling unicode-xid v0.0.4
   Compiling openssl v0.9.12
   Compiling bitflags v0.7.0
   Compiling regex-syntax v0.4.1
   Compiling openssl-probe v0.1.1
   Compiling gcc v0.3.49
   Compiling libc v0.2.23
   Compiling unicode-normalization v0.1.4
error: command failed: 'rustc'
info: caused by: Resource temporarily unavailable (os error 11)
info: backtrace:

stack backtrace:
   0:     0x7fe992b7fa3d - backtrace::backtrace::trace::h024009f066a6a901
   1:     0x7fe992b7fee2 - backtrace::capture::Backtrace::new::hea6d366cd875d5b7
   2:     0x7fe992b7f536 - error_chain::make_backtrace::h7fba8aedc78ce4f7
   3:     0x7fe9927ffba6 - rustup_init::run_multirust::hc749b5422c99477e
   4:     0x7fe9927fd673 - rustup_init::main::h04c4c93cc582fd5e
   5:     0x7fe992ba6eea - panic_unwind::__rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libpanic_unwind/lib.rs:97
   6:     0x7fe992b9e765 - std::panicking::try<(),fn()>
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:332
                         - std::panic::catch_unwind<fn(),()>
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panic.rs:351
                         - std::rt::lang_start
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/rt.rs:57
   7:     0x7fe99193bd1c - __libc_start_main
   8:     0x7fe9927c4208 - <unknown>
error: Could not compile `strsim`.
Build failed, waiting for other jobs to finish...
error: command failed: 'rustc'
info: caused by: Resource temporarily unavailable (os error 11)
info: backtrace:

stack backtrace:
   0:     0x7f10f3e60a3d - backtrace::backtrace::trace::h024009f066a6a901
   1:     0x7f10f3e60ee2 - backtrace::capture::Backtrace::new::hea6d366cd875d5b7
   2:     0x7f10f3e60536 - error_chain::make_backtrace::h7fba8aedc78ce4f7
   3:     0x7f10f3ae0ba6 - rustup_init::run_multirust::hc749b5422c99477e
   4:     0x7f10f3ade673 - rustup_init::main::h04c4c93cc582fd5e
   5:     0x7f10f3e87eea - panic_unwind::__rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libpanic_unwind/lib.rs:97
   6:     0x7f10f3e7f765 - std::panicking::try<(),fn()>
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:332
                         - std::panic::catch_unwind<fn(),()>
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panic.rs:351
                         - std::rt::lang_start
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/rt.rs:57
   7:     0x7f10f2c1cd1c - __libc_start_main
   8:     0x7f10f3aa5208 - <unknown>
error: Could not compile `semver-parser`.
Build failed, waiting for other jobs to finish...
error: command failed: 'rustc'
info: caused by: Resource temporarily unavailable (os error 11)
info: backtrace:

stack backtrace:
   0:     0x7f45c474ca3d - backtrace::backtrace::trace::h024009f066a6a901
   1:     0x7f45c474cee2 - backtrace::capture::Backtrace::new::hea6d366cd875d5b7
   2:     0x7f45c474c536 - error_chain::make_backtrace::h7fba8aedc78ce4f7
   3:     0x7f45c43ccba6 - rustup_init::run_multirust::hc749b5422c99477e
   4:     0x7f45c43ca673 - rustup_init::main::h04c4c93cc582fd5e
   5:     0x7f45c4773eea - panic_unwind::__rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libpanic_unwind/lib.rs:97
   6:     0x7f45c476b765 - std::panicking::try<(),fn()>
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:332
                         - std::panic::catch_unwind<fn(),()>
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panic.rs:351
                         - std::rt::lang_start
```

**Comment by alexcrichton** [comment]
Hm that looks like rustup itself is printing a bunch of errors? Unsure :(

**Comment by alexcrichton** [comment]
I've pushed a [PR to ignore this error](https://github.com/rust-lang/cargo/pull/4116) regardless

**Comment by kozo2** [comment]
Thank you for your comment.
But I still have trouble like this. It seems that I can not move forward from block wait state.
```
klogin9$ cd cargo/
klogin9$ RUST_BACKTRACE=1 /tmp/.cargo/bin/cargo build
    Blocking waiting for file lock on the registry index
```
Information on this supercomputer environment is unpublished.
Therefore, it may be difficult to share information and it may be difficult to solve this issue.
So There is no need to reopen this issue.

I would like to thank you for the courtesy of your reply.

**Comment by alexcrichton** [comment]
Hm are you sure you're using a cargo with #4116?

**Comment by kozo2** [comment]
When the above error occurred I certainly used the code of commit ahead of 4116.
But the situation has also changed.
I got the following error after I ran 'rustup update' and removed and re-cloned Cargo repository.
```

 Downloading foreign-types v0.2.0
 Downloading thread-id v3.1.0
 Downloading backtrace-sys v0.1.10
   Compiling openssl-probe v0.1.1
   Compiling cfg-if v0.1.0
   Compiling foreign-types v0.2.0
   Compiling strsim v0.6.0
   Compiling crossbeam v0.2.10
   Compiling pkg-config v0.3.9
   Compiling log v0.3.8
   Compiling quote v0.3.15
   Compiling dtoa v0.4.1
   Compiling itoa v0.3.1
   Compiling bitflags v0.7.0
   Compiling num-traits v0.1.37
   Compiling regex-syntax v0.4.1
   Compiling serde v1.0.8
   Compiling openssl v0.9.12
   Compiling gcc v0.3.50
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 11, message: "Resource temporarily unavailable" } }', /checkout/src/libcore/result.rs:860
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 11, message: "Resource temporarily unavailable" } }', /checkout/src/libcore/result.rs:860
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 11, message: "Resource temporarily unavailable" } }', /checkout/src/libcore/result.rs:860
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 11, message: "Resource temporarily unavailable" } }', /checkout/src/libcore/result.rs:860
   Compiling utf8-ranges v1.0.0
   Compiling unicode-normalization v0.1.4
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:371
   4: std::panicking::rust_panic_with_hook
                        at /checkout/src/libstd/panicking.rs:549
   5: std::panicking::  at begin_panic
/checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs           :49
  at /checkout/src/libstd/panicking.rs  : 5111
:    std6::: sys_commonstd::backtrace::_print
::panicking           ::begin_panic_fmt  at
/checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
  at            /checkout/src/libstd/panicking.rs:  at 495/checkout/src/libstd/sys_common/backtrace.rs
:  60
7           :   at /checkout/src/libstd/panicking.rs:355
   3: stdrust_begin_unwind::
panicking::           default_hook
  at            /checkout/src/libstd/panicking.rs:  at 471/checkout/src/libstd/panicking.rs
:  371
8  :  core4::panicking::: panic_fmt
std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:549
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:495
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:471
   8: core::panicking::panic_fmt
             at            /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at   at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs/checkout/src/libstd/sys_common/backtrace.rs::4971

      21: : stdstd::::panickingsys_common::::default_hookbacktrace::::{_print{
closure}           }
  at /checkout/src/libstd/sys_common/backtrace.rs           :71  at
/checkout/src/libstd/sys_common/backtrace.rs  : 602
:            std::  at panicking/checkout/src/libstd/panicking.rs:::default_hook355::
{  { closure3}: }
std::           panicking::  at default_hook/checkout/src/libstd/sys_common/backtrace.rs
:60
             at /checkout/src/libstd/panicking.rs  at :/checkout/src/libstd/panicking.rs371:
355
      43: : stdstd::::panickingpanicking::::rust_panic_with_hookdefault_hook

                        at   at /checkout/src/libstd/panicking.rs/checkout/src/libstd/panicking.rs::549371

      54: : stdstd::::panickingpanicking::::begin_panicrust_panic_with_hook

                        at   at /checkout/src/libstd/panicking.rs/checkout/src/libstd/panicking.rs::511549

      65: : stdstd::::panickingpanicking::::begin_panic_fmtbegin_panic

                        at   at /checkout/src/libstd/panicking.rs/checkout/src/libstd/panicking.rs::495511

      76: : rust_begin_unwindstd
::           panicking::  at begin_panic_fmt/checkout/src/libstd/panicking.rs
:471
    at  /checkout/src/libstd/panicking.rs8:: 495core
::  panicking ::7panic_fmt:
rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:471
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:69
   9: core::result::unwrap_failed
  10: rustc_driver::main
  11: __rust_maybe_catch_panic
             at /checkout/src/libcore/panicking.rs:69
   9: core::result::unwrap_failed
  10: rustc_driver::main
  11: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  12: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:433
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:59
  13: __libc_start_main
  14: <unknown>
             at /checkout/src/libpanic_unwind/lib.rs:98
  12: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:433
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:59
  13: __libc_start_main
  14: <unknown>
             at /checkout/src/libcore/panicking.rs:69
   9: core::result::unwrap_failed
  10: rustc_driver::main
  11: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  12: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:433
             at /checkout/src/libstd/panic.rs:361
                        at /checkout/src/libstd/rt.rs:59  at
/checkout/src/libcore/panicking.rs:  6913
: __libc_start_main
 9: core::result::unwrap_failed
  14  : 10<unknown>:
rustc_driver::main
  11: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  12: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:433
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:59
  13: __libc_start_main
  14: <unknown>
error: Could not compile `serde`.
Build failed, waiting for other jobs to finish...
error: Could not compile `bitflags`.
Build failed, waiting for other jobs to finish...
error: Could not compile `crossbeam`.
Build failed, waiting for other jobs to finish...
error: Could not compile `regex-syntax`.
Build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by alexcrichton** [comment]
Are you invoking Cargo from a context which is setting stdout/stdin file descriptors as nonblocking? Otherwise I"m not sure how that error would happen...

**Comment by kozo2** [comment]
I don't know how to invoke Cargo from a context which is setting stdout/stdin file descriptors as nonblocking.
And I did not create any config file in particular.

**Comment by tatsuya6502** [comment]
@kozo2 Do you have Python 3 or 2 installed in your environment? If so, can you please run this "nonblocking.py" on your environment and paste the outputs here? By doing this, we will get better understanding of what is going on about your stdin and stdout.

https://gist.github.com/tatsuya6502/72599e2d9785ec7c7d5e50959d2a2333

For your reference, I put the output from my local Arch Linux environment to the gist.

FYI, this Japanese article will explain how nonblocking works on stdout and what is error 11:
http://qiita.com/kumagi/items/66aa5e3036883d3be7cf

**Comment by kozo2** [comment]
@alexcrichton @tatsuya6502 
I'm sorry for this late reply.
I confirmed that cargo(0.21.0-nightly) worked well on my FEFS environment.
(There was no `failed to lock file` message on my env.)

Thank you.
