### ISSUE TITLE
Panic when attempting to `install --git` with Github provided ssh link

### ISSUE THREAD

**Issue by CAD97** [rust-lang/cargo#4394]
First attempt:

```text
$ cargo +nightly install --git git@github.com:rust-lang-nursery/rustfmt.git
error: invalid url `git@github.com:rust-lang-nursery/rustfmt.git`: relative URL without a base
```

Second attempt:

```text
$ cargo +nightly install --git github.com:rust-lang-nursery/rustfmt.git
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src\libcore\option.rs:335:20
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

With backtrace:

```text
$ set RUST_BACKTRACE=1 && cargo +nightly install --git github.com:rust-lang-nursery/rustfmt.git
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src\libcore\option.rs:335:20
stack backtrace:
   0: git_remote_name
   1: git_remote_name
   2: git_remote_name
   3: git_remote_name
   4: git_remote_name
   5: git_remote_name
   6: git_remote_name
   7: git_remote_name
   8: git_remote_name
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: git_remote_name
  17: git_remote_name
  18: git_note_id
  19: BaseThreadInitThunk
```

Expected: Error message because this is an invalid format (or for it to work)

Actual: Panicked, see above

(Note: installing via the https link worked fine.)

I am on Windows.

**Comment by alexcrichton** [comment]
Thanks for the report! On Linux there's a bit more useful of a backtrace which indicates that the panic comes from [this function](https://github.com/rust-lang/cargo/blob/8720d63bc14e64b66e6f866b37cddd620c01b057/src/cargo/sources/git/source.rs#L73-L104). The `github.com:rust-lang-nursery/rustfmt.git` format is actually an invalid url for Cargo, but we should present a much nicer error message!
