### ISSUE TITLE
Backtrace printed with `--nocapture` even if test succeeds

### ISSUE THREAD

**Issue by sanmai-NL** [rust-lang/cargo#4569]
```sh
cargo test -- --nocapture
```

`lib.rs`:
```
#[cfg(test)]
mod tests {
    use std::panic::catch_unwind;

    #[test]
    fn it_works() {
        assert_eq!(2 + 2, 4);
    }
    
    #[test]
    fn unwind() {
        catch_unwind(|| panic!());
    }
}

```
## Expected
Normal test output when all tests pass. Meaning no backtraces.

## Actual
```
running 2 tests
thread 'tests::unwind' panicked at 'explicit panic', src/lib.rs:12:24
test tests::it_works ... ok
stack backtrace:
   0:     0x5644c950d073 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::ha1fb4114e014c7ae
                               at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x5644c9509350 - std::sys_common::backtrace::_print::h8cb6ca2663711d60
                               at /checkout/src/libstd/sys_common/backtrace.rs:71
   2:     0x5644c950f2b3 - std::panicking::default_hook::{{closure}}::hc17ae9e3f8017993
                               at /checkout/src/libstd/sys_common/backtrace.rs:60
                               at /checkout/src/libstd/panicking.rs:381
   3:     0x5644c950f022 - std::panicking::default_hook::h758877de8a3cb411
                               at /checkout/src/libstd/panicking.rs:397
   4:     0x5644c950f777 - std::panicking::rust_panic_with_hook::h7659ddeb07946f53
                               at /checkout/src/libstd/panicking.rs:577
   5:     0x5644c94ca6a5 - std::panicking::begin_panic::h44d174e5813907d0
                               at /checkout/src/libstd/panicking.rs:538
   6:     0x5644c94cae81 - bla::tests::unwind::{{closure}}::h11541a6b1511b11b
                               at src/lib.rs:12
   7:     0x5644c94ca7b1 - std::panicking::try::do_call::h46e111a7331e077c
                               at /checkout/src/libstd/panicking.rs:480
   8:     0x5644c95165fc - __rust_maybe_catch_panic
                               at /checkout/src/libpanic_unwind/lib.rs:99
   9:     0x5644c94ca6fb - std::panicking::try::h05aa611b2e6bc770
                               at /checkout/src/libstd/panicking.rs:459
  10:     0x5644c94caea3 - std::panic::catch_unwind::hed8ca700536eda68
                               at /checkout/src/libstd/panic.rs:361
  11:     0x5644c94ca5a0 - bla::tests::unwind::h8ceb0c864580d961
                               at src/lib.rs:12
  12:     0x5644c94daa51 - <F as test::FnBox<T>>::call_box::h94b72f6ae1abad68
                               at /checkout/src/libtest/lib.rs:1480
                               at /checkout/src/libcore/ops/function.rs:223
                               at /checkout/src/libtest/lib.rs:141
  13:     0x5644c95165fc - __rust_maybe_catch_panic
                               at /checkout/src/libpanic_unwind/lib.rs:99
  14:     0x5644c94cbe1a - std::sys_common::backtrace::__rust_begin_short_backtrace::ha152502ccc0cc025
                               at /checkout/src/libstd/panicking.rs:459
                               at /checkout/src/libstd/panic.rs:361
                               at /checkout/src/libtest/lib.rs:1419
                               at /checkout/src/libstd/sys_common/backtrace.rs:136
  15:     0x5644c94ccc22 - std::panicking::try::do_call::hcb01a4f06f1c269d
                               at /checkout/src/libstd/thread/mod.rs:400
                               at /checkout/src/libstd/panic.rs:296
                               at /checkout/src/libstd/panicking.rs:480
  16:     0x5644c95165fc - __rust_maybe_catch_panic
                               at /checkout/src/libpanic_unwind/lib.rs:99
  17:     0x5644c94d46c2 - <F as alloc::boxed::FnBox<A>>::call_box::h3fd1975f2d48a5b4
                               at /checkout/src/libstd/panicking.rs:459
                               at /checkout/src/libstd/panic.rs:361
                               at /checkout/src/libstd/thread/mod.rs:399
                               at /checkout/src/liballoc/boxed.rs:728
  18:     0x5644c950e6cb - std::sys::imp::thread::Thread::new::thread_start::h3a39accbdb27ce8a
                               at /checkout/src/liballoc/boxed.rs:738
                               at /checkout/src/libstd/sys_common/thread.rs:24
                               at /checkout/src/libstd/sys/unix/thread.rs:90
  19:     0x7fa96a243089 - start_thread
  20:     0x7fa969d641be - __clone
  21:                0x0 - <unknown>
test tests::unwind ... ok

test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

This happens with `RUST_BACKTRACE=full`. With `RUST_BACKTRACE=0` unnecessary messages still are being emitted:
```
thread 'tests::unwind' panicked at 'explicit panic', src/lib.rs:12:24
note: Run with `RUST_BACKTRACE=1` for a backtrace.
``` 

## Meta
`rustc 1.22.0-nightly (185cc5f26 2017-10-02)`
`cargo 0.23.0-nightly (e447ac7e9 2017-09-27)`

**Comment by lukaslueg** [comment]
Isn't this intended with `--nocapture`? The backtrace is printed by `panicking::default_hook()`, which you can override with `panic::set_hook()`.

```
#[cfg(test)]
mod tests {
    use std::panic;

    #[test]
    fn unwind() {
        panic::set_hook(Box::new(|_| {
            // Silence!
        }));
        panic::catch_unwind(|| panic!());
        let _ = panic::take_hook();
        //panic!("Darn thing");
    }
}

```

**Comment by sanmai-NL** [comment]
```
By default the rust test harness hides output from test execution to
keep results readable. Test output can be recovered (e.g. for debugging)
by passing `--nocapture` to the test binaries:

  cargo test -- --nocapture
```
A backtrace isn't output printed on purpose from test code. It is printed automatically in case of a fatal error. In this case, there isn’t a fatal error.

**Comment by lukaslueg** [comment]
`catch_unwind` buys you being still alive after the closure has panicked. The panic itself is still happening and the default hook executes, [printing it's thing to stderr](https://github.com/rust-lang/rust/blob/a80a873209a79499290201f8657618703a51b73e/src/libstd/panicking.rs#L338), and then returning (via `catch_unwind`) to your code. By the time the test calls `exit(0)`, the backtrace has already been printed. Cargo can't distinguish the test binary's panic-output from 

```rust
#[test]
fn it_works() {
    eprintln!("Now hear this!");
}
```

which would also print on `--nocapture` and then succeed. The backtrace is no different than a simple `eprintln`.

Am I missing your point?

**Comment by alexcrichton** [comment]
Thanks for the report! I think this has to do with the test harness in rustc itself though, so I'm going to close this. Feel free to open an issue with rust-lang/rust!
