### ISSUE TITLE
Panic when searching for "emoji"

### ISSUE THREAD

**Issue by BrainBlasted** [rust-lang/cargo#4771]
This is something I found today, on the latest nightly from rustup.
```
$ cargo search emoji
    Updating registry `https://github.com/rust-lang/crates.io-index`
thread 'main' panicked at 'byte index 127 is not a char boundary; it is inside '👣' (bytes 124..128) of `Convert everything to Emojis. - 🐫🔦🔥🎲🐬🍀🍟🔋🐬🎲🐬🍀🎁🍟💧👂🔥🚪🔋🍟🔦🔋🚗👣🔦🌍👂🍤🐗`', /checkout/src/libcore/str/mod.rs:2235:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
With RUST_BACKTRACE=1:
```
    Updating registry `https://github.com/rust-lang/crates.io-index`
thread 'main' panicked at 'byte index 127 is not a char boundary; it is inside '👣' (bytes 124..128) of `Convert everything to Emojis. - 🐫🔦🔥🎲🐬🍀🍟🔋🐬🎲🐬🍀🎁🍟💧👂🔥🚪🔋🍟🔦🔋🚗👣🔦🌍👂🍤🐗`', /checkout/src/libcore/str/mod.rs:2235:4
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at /checkout/src/libstd/sys_common/backtrace.rs:68
             at /checkout/src/libstd/sys_common/backtrace.rs:57
   2: _ZN3std9panicking12default_hook28_$u7b$$u7b$closure$u7d$$u7d$17h2b916ce9014fa45bE.llvm.1259EE4F
             at /checkout/src/libstd/panicking.rs:381
   3: _ZN3std9panicking12default_hook17h31f8f0083a158559E.llvm.1259EE4F
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: _ZN3std9panicking11begin_panic17hc624dc80491e13d2E.llvm.1259EE4F
             at /checkout/src/libstd/panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:498
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
   9: core::str::slice_error_fail
             at /checkout/src/libcore/str/mod.rs:0
  10: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &'a mut F>::call_once
  11: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
  12: cargo::ops::registry::search
  13: cargo::search::execute
  14: _ZN5cargo27try_execute_builtin_command17h895cb77e23517fb9E.llvm.A0850878
  15: _ZN5cargo7execute17h83545a00fd9d999cE.llvm.A0850878
  16: _ZN5cargo23call_main_without_stdin17h3256f0378112ac6eE.llvm.A0850878
  17: _ZN5cargo4main17hd2f7e5aaaa767496E.llvm.A0850878
  18: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:101
  19: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/rt.rs:58
  20: __libc_start_main
  21: <unknown>
```

**Comment by lukaslueg** [comment]
working this
