### ISSUE TITLE
cargo test --all doesn't account for the features flag?

### ISSUE THREAD

**Issue by nbaksalyar** [rust-lang/cargo#5467]
When I run `cargo test --all --features "abc def"`, seemingly the features are not passed down to the workspace crates at all as the compilation process proceeds as if no features were passed, which is not an expected behaviour. On the other hand, if I use the `--all-features` flag (as `cargo test --all --all-features`), it works, but it is not applicable for all cases as in certain conditions some of the features don't need to be included.

This behaviour is demonstrated by this repository: https://github.com/nbaksalyar/cargo-test-all
It consists of a single project in the workspace named `abc`. It has two features: `ghi` and `def`. The build will succeed only if a single feature `def` is included, so you can try the following commands:

Unexpected outcome:
```
cargo-test-all $ cargo test --all --features "def"
test tests::it_works ... FAILED
... thread 'tests::it_works' panicked at 'def feature is not switched on', abc/src/lib.rs:12:9
```

Expected, but not desirable outcome:
```
cargo-test-all $ cargo test --all --all-features
test tests::fail ... FAILED
	thread 'tests::fail' panicked at 'ghi feature is switched on', abc/src/lib.rs:6:9
```

Expected and desirable outcome:
```
cargo-test-all $ cd abc
abc $ cargo test --features "def"
...
test result: ok.
```

So the final case, when we run the project in the workspace individually with `--features "def"`, is the behaviour expected from `cargo test --all --features "def"`. If it is intended to be this way, then it needs to be documented.

**Comment by nbaksalyar** [comment]
Sorry, wrongly reported - it is fixed by updating to latest stable RustC (1.25.0).
