### ISSUE TITLE
Assertion error when clean is combined with -p flag.

### ISSUE THREAD

**Issue by tkaitchuck** [rust-lang/cargo#8149]
**Problem**
In cargo 1.43.0 (3532cf738 2020-03-17)  but not in 1.42 the following assertion can be triggered when running `cargo clean -p my-package`:
```
thread 'main' panicked at 'assertion failed: self.host', src/tools/cargo/src/cargo/core/profiles.rs:920:13
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1063
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
  11: std::panicking::begin_panic
  12: cargo::core::compiler::unit_dependencies::compute_deps
  13: cargo::core::compiler::unit_dependencies::deps_of
  14: cargo::core::compiler::unit_dependencies::deps_of_roots
  15: cargo::core::compiler::unit_dependencies::build_unit_dependencies
  16: cargo::ops::cargo_clean::clean
  17: cargo::commands::clean::exec
  18: cargo::cli::main
  19: cargo::main
  20: std::rt::lang_start::{{closure}}
  21: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  22: std::panicking::try::do_call
             at src/libstd/panicking.rs:303
  23: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  24: std::panicking::try
             at src/libstd/panicking.rs:281
  25: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  26: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  27: main
  28: __libc_start_main
  29: <unknown>
```

**Steps**
1. Use Rustup to upgrade to cargo 1.43.0
2. enter into a package directory
3. run `cargo clean -p package-name` where "package-name" is a valid package name to be cleaned.

**Notes**
`cargo clean` without the `-p` flag works fine.

Output of `cargo version`:
cargo 1.43.0 (3532cf738 2020-03-17)
This is running on x86_64 GNU/Linux .

**Comment by ehuss** [comment]
Thanks for the report. I can't quite figure out a way to reproduce this. Is this in a public repo that I can look at?  If not, do you think you could create a reproduction?

**Comment by tkaitchuck** [comment]
@ehuss I have invited you to the repository. You can see how the code is being invoked in the `.github/workflows/cibuild.yml` config file.

**Comment by ehuss** [comment]
Thanks @tkaitchuck!  I see the problem, it is embarrassingly easy to hit (`cargo clean -p foo` for any foo with a build dependency).  

`cargo clean -p` has had a long history of not working very well.  I'm taking a look to see if there is some slightly better approach for how it can work.
